### ISSUE TITLE
FR: allow per-entity smoothing

### ISSUE THREAD

**Issue by garyo** [kalkih/mini-graph-card#1140] opened 2024-09-15 13:31 UTC
I would love to replace my ApexCharts cards (which are slow to refresh, though super flexible) with mini-graph-cards. Here's a sample of my main ApexCharts card: instantaneous power use, overlaid with smoothed one hour moving average:
<img width="358" alt="image" src="https://github.com/user-attachments/assets/500f0a94-81de-400a-85df-f153500341a5">

If I could set smoothing and points_per_hour independently per entity (i.e. per line in the graph), I could probably get close to this.

**Comment by ildar170975** [comment] 2024-09-15 19:01
Duplicate of https://github.com/kalkih/mini-graph-card/issues/1039

**Closed by ildar170975** 2024-09-15 19:01 UTC
