### ISSUE TITLE
24 hours doesn't show good time 

### ISSUE THREAD

**Issue by r3mcos3** [kalkih/mini-graph-card#314] opened 2020-03-25 10:00 UTC
I've had a issue with the 24 hours notation. 
look at picture.

24:31 has to be 00:31 right??

![minigraphcard](https://user-images.githubusercontent.com/45529818/77524434-a076c500-6e87-11ea-9116-1664de83c5cf.jpg)

```
`color_thresholds:
  - color: '#0061fc'
    value: 250
  - color: e3fc00
    value: 500
  - color: '#fc0000'
    value: 750
entities:
  - sensor.speedtest_download
hour24: true
hours_to_show: 168
icon: 'mdi:download-network'
show:
  extrema: true
type: 'custom:mini-graph-card'`
```

**Comment by kalkih** [comment] 2020-03-25 19:58
Haha, interesting.
Not really sure how this is happening, should be handled correctly by the browser.

**Comment by ACrazyConcept** [comment] 2020-05-07 01:35
Same for me. And I suspect it is also the reason my bar charts cannot show correct graph.
![image](https://user-images.githubusercontent.com/36438756/81244847-c1e4d800-9013-11ea-86ac-1956854fae10.png)

**Comment by RomRider** [comment] 2021-01-20 00:20
Duplicate of #536

**Closed** 2021-01-20 00:19 UTC
Labels: bug, duplicate
