### ISSUE TITLE
Add commas for large numbers (true/false)

### ISSUE THREAD

**Issue by fireheadman** [kalkih/mini-graph-card#509] opened 2020-12-08 06:47 UTC
Using your graph tool for COVID-19
Would be great to have commas in the number for a more dramatic look

<img width="360" alt="image" src="https://user-images.githubusercontent.com/19847195/101449766-9e09ad80-38e6-11eb-86f5-2a4dd934d25a.png">

**Comment by RomRider** [comment] 2021-01-18 09:02
Duplicate of #495

**Closed by RomRider** 2021-01-18 09:02 UTC
Labels: enhancement, feature request
