### ISSUE TITLE
Will the plugin have plans to support attributes？

### ISSUE THREAD

**Issue by xianweitudou** [kalkih/mini-graph-card#543] opened 2021-01-20 08:56 UTC
Thank you so much for bringing us such an excellent plugin。

**Comment by RomRider** [comment] 2021-01-20 08:59
There is already a discussion about that in #411. I'll close it in favor of the other one.

**Comment by RomRider** [comment] 2021-01-20 08:59
Duplicate of #411

**Closed by RomRider** 2021-01-20 08:59 UTC
Labels: duplicate, feature request
