### ISSUE TITLE
Card fails when hass is not defined in HA 0.110.

### ISSUE THREAD

**Issue by RomRider** [kalkih/mini-graph-card#358] opened 2020-05-21 11:56 UTC
With HA 0.110 it happens that the `hass` object is `undefined`.
mini-graph-card fails with `cannot access states of undefined` from here https://github.com/kalkih/mini-graph-card/blob/master/src/main.js#L59

I've managed to fix the issue on my end with 
```js
  set hass(hass) {
    if (!hass) return;
    if (!this._hass && hass) { // without this, it wouldn't display the first time, unless using the reload from the HA top right menu
      setTimeout(() => {
        this.updateData();
      }, 1000);
    }
........
```

But I feel the fix is very ugly so I didn't PR it. Let me know what you think.

I can make this fail by putting mini-graph-card inside a picture-elements card.

**Comment by alesoft73** [comment] 2020-05-21 12:02
I have the same problem.
Many thanks!

**Comment by RomRider** [comment] 2020-05-21 12:37
Might be related to https://github.com/home-assistant/frontend/issues/5965

**Comment by kalkih** [comment] 2020-05-21 12:53
Hello, thanks for debugging it.

Hmm, Interesting, I guess even if it isn't supposed to happen and might get fixed in core it wouldn't hurt to check the hass object before accessing it.

What do you think about this? https://github.com/kalkih/mini-graph-card/pull/359

**Comment by RomRider** [comment] 2020-05-21 12:56
So apparently it will get fixed in core as per a comment on the bug I've opened in frontend, but #359 is the first thing I've tried and the result was it didn't load the graph initially, unless you'd use the "reload" from the menu.

**Comment by kalkih** [comment] 2020-05-21 13:04
Okay, not able to reproduce that, seem to render correctly for me with that change.

**Closed** 2021-01-17 19:26 UTC
Labels: bug
