### ISSUE TITLE
show_state doesn't work on the first entity

### ISSUE THREAD

**Issue by Nickduino** [kalkih/mini-graph-card#1144] opened 2024-09-25 18:16 UTC
Use case: I want to see the graph but not the numerical value

![image](https://github.com/user-attachments/assets/703b1179-74ad-41d4-ae89-25cdd8912df4)

If you have two entities, you can't hide the state of the **first** one:

![image](https://github.com/user-attachments/assets/cfcdca83-762d-4c6f-ae13-7a5d198c89e3)
(It works with the second one)

**Comment by ildar170975** [comment] 2024-09-27 19:12
Duplicate of https://github.com/kalkih/mini-graph-card/issues/1123
It is by a design. 
If you need a different behavior - consider registering a detailed Feature Request.

**Closed by ildar170975** 2024-09-27 19:12 UTC

**Comment by Nickduino** [comment] 2024-09-27 20:41
> If you need a different behavior - consider registering a detailed Feature Request.

https://github.com/kalkih/mini-graph-card/issues/1150
