### ISSUE TITLE
"hours_to_show" not working

### ISSUE THREAD

**Issue by chemelli74** [kalkih/mini-graph-card#272] opened 2020-02-18 14:19 UTC
Hi,

I have implemented 2 cards using v0.9.2 on HA 0.105.2.
First one with:

```
show:
  hours_to_show: 8
```

and second one with:

```
show:
  graph: bar
  hours_to_show: 168
```

but on both cases is not correctly filtering the time range, showing a lot of data more.
For example at 3pm,  the first graph shows data from 5am.

Am I missing something ?

Simone

**Comment by kalkih** [comment] 2020-02-18 18:12
Never seen that, set `points_per_hour` to `1` as well and send me screenshots of the graphs.

**Comment by SouravBasu** [comment] 2020-02-19 01:28
I see a problem with bar graph. My config: 

```
          - type: custom:mini-graph-card
            entities:
              - sensor.sprinkler_duration_template
            name: Sprinkler Duration
            icon: mdi:water-pump
            line_color: "#4285F4"
            animate: true
            hours_to_show: 168
            points_per_hour: 1
            aggregate_func: max
            group_by: date
            hour24: true
            show:
              graph: bar
            tap_action: 
              action: more-info
              entity: switch.backyard_irrigation
```

This always shows the first bar as zero. Even if I change the number days by setting the hours_to_show to 144 or 48, the first bar is always zero.

![image](https://user-images.githubusercontent.com/153128/74793066-1cbc2e00-5274-11ea-92da-026921cc5fcc.png)

**Comment by SouravBasu** [comment] 2020-02-19 01:30
hour_to_show: 144
![image](https://user-images.githubusercontent.com/153128/74793111-41180a80-5274-11ea-90f2-a083e8b3fd72.png)


hours_to_show: 48
![image](https://user-images.githubusercontent.com/153128/74793145-58ef8e80-5274-11ea-968e-1e5bc8f44767.png)

**Comment by kalkih** [comment] 2020-02-19 16:44
Please try updating the card, clear cache e.t.c.
If you've installed through HACS, try reinstalling the card and double check and make sure your resource reference match the one stated in HACS.

**Comment by SouravBasu** [comment] 2020-02-19 19:31
I have the latest - 0.9.2. I did a manual install and not through HACS. I also cleared all browser caches. Still the same.

**Comment by kalkih** [comment] 2020-02-19 19:48
Okay, I'm not able to reproduce that issue.
If you open your browser's developer tools and go to the network tab, refresh the page with the graph on it and check for a call like this:
<img width="524" alt="Screenshot 2020-02-19 at 20 45 58" src="https://user-images.githubusercontent.com/457678/74869815-f3c19900-5358-11ea-87de-6fb23cae141a.png">
The request should include two dates in the url, what dates do you see?

You might want to set the card option `cache: false` for the request to show up correctly.

**Comment by chemelli74** [comment] 2020-02-19 22:14
> hour_to_show: 144
> [...] 
> hours_to_show: 48
> [...]

hour_to_show or hours_to_show ?!?!

Simone

**Comment by chemelli74** [comment] 2020-02-19 22:15
>             hours_to_show: 168
>             points_per_hour: 1
>             show:
>               graph: bar

hours_to_show is inside or outside "show:" ?

Simone

**Comment by kalkih** [comment] 2020-02-19 22:18
Outside

**Comment by chemelli74** [comment] 2020-02-19 22:25
Still not working here :-(

![image](https://user-images.githubusercontent.com/57354320/74882258-1068cb80-536f-11ea-9c38-a7c2c39d7da4.png)

Please let me know where I'm wrong.

Simone

**Comment by SouravBasu** [comment] 2020-02-20 00:44
It works fine when it's not hitting the cache. So everytime I see that call in the debugger it works fine. 

When I don't see the call, it shows zero for the first bar.

**Comment by kalkih** [comment] 2020-02-20 16:49
> Still not working here :-(
> 
> ![image](https://user-images.githubusercontent.com/57354320/74882258-1068cb80-536f-11ea-9c38-a7c2c39d7da4.png)
> 
> Please let me know where I'm wrong.
> 
> Simone
I don't understand what the issue is?
What exactly is the issue? Please clarify, what do you expect and what result do you get?


> It works fine when it's not hitting the cache. So everytime I see that call in the debugger it works fine.
> 
> When I don't see the call, it shows zero for the first bar.

Please open a separate issue where we can track this since it's not really related to this one

**Comment by chemelli74** [comment] 2020-02-20 18:58
> I don't understand what the issue is
> What exactly is the issue? Please clarify, what do you expect and what is the result you get?

Sorry, I misread reasult. Now it's working as expected.
Should I close the issue or you close it ?

Simone

**Comment by kalkih** [comment] 2020-02-20 19:07
Okay, great!
I can close it, doesn't really matter who does it 🙂 
Thanks!

**Closed by kalkih** 2020-02-20 19:07 UTC
