### ISSUE TITLE
Request: Ability to apply "decimals:" attribute to entities

### ISSUE THREAD

**Issue by Talk2Giuseppe** [kalkih/mini-graph-card#685] opened 2022-01-09 16:03 UTC
Currently, appears that the decimals attribute can only be applied to the whole card.  Can we request the ability to apply that to an entity?

Example: Bitcoin Wallet contains very small amount of BTC and to display it requires 4 or more decimal places.  But when converted to dollar value, we only need 2 decimal places.

Thank you!

**Comment by Talk2Giuseppe** [comment] 2022-01-14 15:58
> Hi, I'm planning a refactor to allow all (sensible) properties to be provided on an entity level too. `decimals:` will be a part of that :)

Awesome!  Thanks for the reply!

**Comment by Misiu** [comment] 2022-01-16 12:43
Really looking forward to the new version of this awesome card!

**Comment by ildar170975** [comment] 2024-01-19 00:27
Duplicate of https://github.com/kalkih/mini-graph-card/issues/863

**Closed by ildar170975** 2024-01-19 00:27 UTC
Labels: duplicate, enhancement
