### ISSUE TITLE
Formatting: respect the locale

### ISSUE THREAD

**Issue by Nickduino** [kalkih/mini-graph-card#1142] opened 2024-09-25 15:08 UTC
I'm in France and CO2 should display **1 221 ppm** (with a SPACE between the 1 and 2) instead of **1,221 ppm**.

The sensor card does it:

![image](https://github.com/user-attachments/assets/d9b7330c-7a7a-4663-a279-6da9b4a4dd8f)

I didn't see a setting for it on the [mini-graph-card](https://github.com/kalkih/mini-graph-card). Would it be possible to add it?

**Comment by ildar170975** [comment] 2024-09-27 19:06
Duplicate of https://github.com/kalkih/mini-graph-card/issues/1010

**Closed by ildar170975** 2024-09-27 19:06 UTC

**Comment by Nickduino** [comment] 2024-09-27 20:24
My bad, sorry
