### ISSUE TITLE
Feature request: Grid in background

### ISSUE THREAD

**Issue by Draggon** [kalkih/mini-graph-card#400] opened 2020-07-13 15:23 UTC
Hi

The only two things I'm missing in Your graph are
- grid in background 
- labels in case of multiple values at top

Something like:
![image](https://user-images.githubusercontent.com/2098284/87322175-619b7680-c52d-11ea-83d3-e471cd0bc33d.png)

**Comment by Salamandar** [comment] 2020-11-04 16:26
Yeah. Having vertical lines to see days in a week graph would be great !

**Comment by pdeelen** [comment] 2020-11-22 10:36
love to see this function!

**Comment by ipa64** [comment] 2020-11-29 14:50
And please with scale label X and Y

**Comment by RomRider** [comment] 2021-01-17 19:37
Duplicate of #21

(let's discuss it there while I'm trying to wrap my head around the codebase :))

**Closed by RomRider** 2021-01-17 19:37 UTC
