### ISSUE TITLE
Unable to see graphs after 0.2.3

### ISSUE THREAD

**Issue by mokshmridul** [kalkih/mini-graph-card#47] opened 2019-02-13 19:18 UTC
I am unable to see the graphs for the Load and the Temp / Humidity Sensor after upgrade to 0.2.3. My configurations are below:

```cards:
  - entities:
      - light.ceiling_bulb
      - fan.ceiling_fan
      - light.ceiling_light
      - switch.ac
    image: /local/bedroom.jpg
    title: Bedroom
    type: picture-glance
  - cards:
      - cards:
          - entities:
              - sensor.temperature
            font_size: 75
            line_color_threshold:
              - color: '#2a8fce'
                value: 1
              - color: '#33ce2b'
                value: 10
              - color: '#f39c12'
                value: 24
              - color: '#d35400'
                value: 28
              - color: '#c0392b'
                value: 30
            line_width: 5
            location_icon: left
            location_state: center
            show:
              extrema: true
              points: false
            type: 'custom:mini-graph-card'
          - entities:
              - sensor.humidity
            font_size: 75
            line_color_threshold:
              - color: '#33ce2b'
                value: 1
              - color: '#f39c12'
                value: 30
              - color: '#d35400'
                value: 35
              - color: '#c0392b'
                value: 40
            line_width: 5
            location_icon: left
            location_state: center
            show:
              extrema: true
              points: false
            type: 'custom:mini-graph-card'
        type: horizontal-stack
    type: horizontal-stack
  - entity: weather.weather_forecast
    type: weather-forecast
  - artwork: cover
    entity: media_player.mokshs_tv
    hide_power: true
    icon: 'mdi:cast'
    max_volume: 30
    power_color: true
    scroll_info: true
    show_progress: true
    show_source: true
    type: 'custom:mini-media-player'
type: vertical-stack


`cards:
  - cards:
      - cards:
          - cards:
              - entities:
                  - sensor.load_1m
                font_size: 75
                line_color_threshold:
                  - color: '#2a8fce'
                    value: 0.01
                  - color: '#f39c12'
                    value: 2
                  - color: '#d35400'
                    value: 3
                  - color: '#c0392b'
                    value: 4
                line_width: 5
                name: Load 1M
                show:
                  extrema: true
                  points: false
                type: 'custom:mini-graph-card'
              - entities:
                  - sensor.load_5m
                font_size: 75
                line_color_threshold:
                  - color: '#2a8fce'
                    value: 0.01
                  - color: '#f39c12'
                    value: 2
                  - color: '#d35400'
                    value: 3
                  - color: '#c0392b'
                    value: 4
                line_width: 5
                name: Load 5M
                show:
                  extrema: true
                  points: false
                type: 'custom:mini-graph-card'
              - entities:
                  - sensor.load_15m
                font_size: 75
                line_color_threshold:
                  - color: '#2a8fce'
                    value: 0.01
                  - color: '#f39c12'
                    value: 2
                  - color: '#d35400'
                    value: 3
                  - color: '#c0392b'
                    value: 4
                line_width: 5
                name: Load 15M
                show:
                  extrema: true
                  points: false
                type: 'custom:mini-graph-card'
            type: horizontal-stack
        type: horizontal-stack
      - entities:
          - entity: sensor.wan_ip_address
            icon: 'mdi:wan'
        show_header_toggle: false
        type: entities
      - cards:
          - entities:
              - sensor.speedtest_download
            font_size: 75
            line_color_threshold:
              - color: '#c0392b'
                value: 0
              - color: '#d35400'
                value: 4
              - color: '#f39c12'
                value: 6
              - color: '#2a8fce'
                value: 8
            line_width: 5
            name: Test Download
            show:
              points: false
            type: 'custom:mini-graph-card'
          - entities:
              - sensor.speedtest_upload
            font_size: 75
            line_color_threshold:
              - color: '#c0392b'
                value: 0
              - color: '#d35400'
                value: 4
              - color: '#f39c12'
                value: 6
              - color: '#2a8fce'
                value: 8
            line_width: 5
            name: Test Upload
            show:
              points: false
            type: 'custom:mini-graph-card'
          - entities:
              - sensor.speedtest_ping
            font_size: 75
            line_color_threshold:
              - color: '#2a8fce'
                value: 0
              - color: '#f39c12'
                value: 60
              - color: '#d35400'
                value: 80
              - color: '#c0392b'
                value: 100
            line_width: 5
            name: Test Ping
            show:
              points: false
            type: 'custom:mini-graph-card'
        type: horizontal-stack
      - cards:
          - decimals: 0
            entities:
              - sensor.freebsd_router_kbytesec_received
            font_size: 75
            line_color: '#2a8fce'
            line_width: 5
            name: Down Speed
            show:
              points: false
            type: 'custom:mini-graph-card'
          - decimals: 0
            entities:
              - sensor.freebsd_router_kbytesec_sent
            font_size: 75
            line_color: '#f39c12'
            line_width: 5
            name: Up Speed
            show:
              points: false
            type: 'custom:mini-graph-card'
          - entities:
              - sensor.moksh_s_webserver
            font_size: 75
            line_color_threshold:
              - color: '#c0392b'
                value: 30
              - color: '#d35400'
                value: 60
              - color: '#2a8fce'
                value: 90
            line_width: 5
            name: Cert Validity
            show:
              points: false
            type: 'custom:mini-graph-card'
        type: horizontal-stack
      - entities:
          - entity: sensor.plex_server
            hold_action:
              action: call-service
              service: script.restart_pms
          - entity: sensor.sonarr
            hold_action:
              action: call-service
              service: script.restart_sonarr_service
          - entity: sensor.radarr
            hold_action:
              action: call-service
              service: script.restart_radarr_service
          - entity: sensor.bazarr
            hold_action:
              action: call-service
              service: script.restart_bazarr_service
          - entity: sensor.jackett
            hold_action:
              action: call-service
              service: script.restart_jackett_service
          - entity: sensor.ombi
            hold_action:
              action: call-service
              service: script.restart_ombi_service
          - entity: sensor.tautulli
            hold_action:
              action: call-service
              service: script.restart_tautulli_service
          - entity: sensor.mosquitto
            hold_action:
              action: call-service
              service: script.restart_mosquitto_service
          - entity: sensor.unifi
            hold_action:
              action: call-service
              service: script.restart_unifi_service
          - entity: binary_sensor.home_server
        show_name: false
        show_state: true
        title: Service Status
        type: glance
    type: vertical-stack
type: vertical-stack

Screenshot for reference
![chrome_auohikbs2o](https://user-images.githubusercontent.com/8089422/52737400-418f1d00-2ff2-11e9-98af-eca070c24f76.png)

**Comment by kalkih** [comment] 2019-02-13 19:21
Thanks,
I did, unfortunately, break the extrema with the latest release, new release incoming in a few minutes.

Fix for the issue: https://github.com/kalkih/mini-graph-card/commit/f5b191e80d993276e6a4b05ee3509c0e26a75ef3

**Comment by mokshmridul** [comment] 2019-02-13 19:23
> d, unfortunately, break the extrema with the latest release, new release incoming in a few minutes

Thanks a ton.

I thought i messed up again :P

**Comment by kalkih** [comment] 2019-02-13 19:32
There we go, new version is up [v0.2.4](https://github.com/kalkih/mini-graph-card/releases/tag/v0.2.4).
Please let me know if the issue is fixed, thanks!

**Comment by mokshmridul** [comment] 2019-02-13 19:38
@kalkih the graphs are now appearing, but the color stays constant, even though I've set limits using the new feature

Thanks.

**Comment by kalkih** [comment] 2019-02-13 19:41
@mokshmridul 
Sorry forgot to mention but I had also missed to update the docs fully in the previous release.
`line_color_threshold` should in fact have be `color_thresholds`.

Let me know if that solves it!

**Comment by mokshmridul** [comment] 2019-02-13 20:13
It solves it for some of the graphs, but some graphs are not being displayed, and chrome is giving the following error in the console (i cleared my cache and rechecked, but still getting an error)

```mini-graph-card-bundle.js?v=0.2.0:1 Uncaught (in promise) TypeError: Cannot read property 'unit_of_measurement' of undefined
    at HTMLElement.computeUom (mini-graph-card-bundle.js?v=0.2.0:1)
    at k.abs.map.a (mini-graph-card-bundle.js?v=0.2.0:1)
    at Array.map (<anonymous>)
    at HTMLElement.renderInfo (mini-graph-card-bundle.js?v=0.2.0:1)
    at HTMLElement.render (mini-graph-card-bundle.js?v=0.2.0:1)
    at HTMLElement.update (mini-graph-card-bundle.js?v=0.2.0:1)
    at HTMLElement.performUpdate (mini-graph-card-bundle.js?v=0.2.0:1)
    at HTMLElement._enqueueUpdate (mini-graph-card-bundle.js?v=0.2.0:1)

**Comment by kalkih** [comment] 2019-02-13 20:27
Strange, looks like the same error as before.
![capture](https://user-images.githubusercontent.com/457678/52741591-054dc380-2fd6-11e9-81d5-d49017544a9b.PNG)

Could you try bumping the `?v` at the end of the resource reference to `?v=0.2.4`?

**Comment by kalkih** [comment] 2019-02-13 20:28
What does the error say at the top of the stacktrace?
Same as the one I posted above?

**Comment by mokshmridul** [comment] 2019-02-13 20:31
@kalkih doing this seems to have fixed the issues.

Thanks mate.

**Comment by kalkih** [comment] 2019-02-13 20:49
Perfect, thanks, closing this since it's resolved.
If you have more issues or ideas, don't hesitate to open another one.

**Closed by kalkih** 2019-02-13 20:49 UTC
Labels: bug
