### ISSUE TITLE
Possibility to use the 'Line color object' per entity instead of as a general property

### ISSUE THREAD

**Issue by Thumbleweed** [kalkih/mini-graph-card#368] opened 2020-06-06 15:40 UTC
Hi there,
I would love to use the 'line color object' feature you provided.
However, at this point it's not possible to use them per entity. This means that the threshold values and colors will be the same for every graph shown.

Since there is a possibility to have two Y-axis, I would assume that it's not an odd question that at least two 'line color objects' (one per Y-axis) could be defined.

**Comment by kalkih** [comment] 2020-06-07 16:40
Hello,
Color threshold is currently a global setting and can't be set per entity/axis, you can however override the color on specific entities by specifying the `color` option on the entity/entities.

Duplicate of #153, #141

**Closed by kalkih** 2020-06-07 16:40 UTC
Labels: duplicate, feature request
