### ISSUE TITLE
Aggregate functions calculate wrong values?

### ISSUE THREAD

**Issue by emign** [kalkih/mini-graph-card#711] opened 2022-01-29 16:46 UTC
Hallo,

I believe, that the data source for the aggregate functions does not reflect the correct data. I found, that mini-graph gives different results for the aggregate functions than comparable queries on the influxdb data for the same time-intervals.
 
I use this wonderful card for displaying statistics for my Heatpump COP. I will explain the issue with example data of January 27. 2022.

**Collected sensor**
  `sensor.cop_ohne_dhw`

**Mini graph card configuration**
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cop_ohne_dhw
    aggregate_func: avg
    name: Avg
    color: blue
name: COP
hours_to_show: 168
group_by: date
```

**Visualisation**
<img width="463" alt="Home-Dashboard - Home Assistant 2022-01-29 17-08-55" src="https://user-images.githubusercontent.com/5278352/151668157-8d7a2329-3ceb-4b4b-8d50-364516b585a1.png">

**What I want to achieve**
Display the average COP for each day.

**Problem**
The values in mini-graph differ from the correct values (see this google spreadsheet which contains all values from Jan 27 and Jan 28. There I also show other aggregate functions) extracted with this influx query:
```
SELECT "value" AS "mean_value" FROM "haDatabase"."autogen"."state" WHERE time > '2022-01-27T00:00:00Z' AND time < '2022-01-27T23:59:59Z' AND "entity_id"='cop_ohne_dhw'
```

- avg COP calculated in mini graph for Jan 27: 3.83
- avg COP calculated from the actual values (from influxdb): 3,95 (see here [Google Spreadsheet with exported values](https://docs.google.com/spreadsheets/d/1LTAf0u0F6NuQ6PbJeYIaCSQvcCamCSdh_k6JCTZuJPo/edit?usp=sharing)
- sum COP calculated in mini graph for Jan 27: 2829,09
- sum COP calculated from the actual values (from influxdb): 2774,601 
- max COP calculated in mini graph for Jan 27: 15,04
- max COP calculated from the actual values (from influxdb): 18,56 
- min COP calculated in mini graph for Jan 27: 9
- min COP calculated from the actual values (from influxdb): 0 

<img width="451" alt="Home-Dashboard - Home Assistant 2022-01-29 17-10-53" src="https://user-images.githubusercontent.com/5278352/151668257-27de7ed8-f9e5-4667-9a30-184db3a58a2e.png">

**Question**
Am I overlooking something? Is it maybe a timezone problem?

**Comment by R5fan** [comment] 2022-02-01 15:58
I have the same problem. I think the average is calculated per data point or something? However, my sensors dont update if there is no change in data, so some power sensors may be at 0W for many hours and then some spikes, and the average is completely wrong. As an example running my microwave for 4 mins:

![image](https://user-images.githubusercontent.com/1439530/152003314-2b010a14-3e45-476f-9b4c-462af3793b6e.png)

mini-graph card gives me an average of 590W !

**Comment by jlsjonas** [comment] 2022-02-01 22:37
Sounds like a duplicate of #618, thanks for the extra insights though!

We'll hopefully be able to tackle this sometime soon, but after the configuration update.

**Closed** 2022-02-01 22:37 UTC
