### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by QonosSWE** [kalkih/mini-graph-card#71] opened 2019-03-12 20:49 UTC
Hi,
I would love to change the icon to a battery and when battery is down to, lets say 10% i would use this "mdi:battery-10", end then change the color to red. red and flashing would be even better.

(dont even know if this is possible to do in lovelace today)

**Comment by kalkih** [comment] 2019-03-12 21:12
Kind of duplicate of #50, will close this, please comment in that issue if you wish to discuss this request further.

**Closed by kalkih** 2019-03-12 21:12 UTC
Labels: duplicate
