### ISSUE TITLE
Unable to use template sensor

### ISSUE THREAD

**Issue by Tinkergnome621** [kalkih/mini-graph-card#674] opened 2021-12-23 16:51 UTC
The only way I was able to convert a couple of sensors from °f to °c was to create a template sensor with the maths to convert them.  For whatever reason in the latest version of HA customize.yaml unit_of_measurement does not work.  I can add the sensor using standard lovelace history graph card as well as others.

I have tried both

- sensor.sensor_drybox_si7021_dewpoint_c

- sensor_drybox_si7021_dewpoint_c

Both give the same results.... any direction to go to fix this would be greatly appriciated

### ### 
Config using default sensor
![t1](https://user-images.githubusercontent.com/47935126/147269541-030a92ea-5a51-4346-a780-709ca0db5fb9.PNG)

config using template sensor
![t2](https://user-images.githubusercontent.com/47935126/147269566-0545b93b-1809-4665-94b7-0ed3954a00ef.PNG)

debug showing sensors
![t3](https://user-images.githubusercontent.com/47935126/147269584-9ba65f36-c749-43fd-9faa-6e266cdbd4f8.PNG)

**Comment by kalkih** [comment] 2021-12-29 10:20
The entity should be specified as `sensor.sensor_drybox_si7021_dewpoint_c`, according to what's showed in the last screenshot.
Please try again, could perhaps also been that no history data was saved yet.

**Comment by scyto** [comment] 2022-01-10 01:46
this would be an awesome function to have natively in this card - is that possible?

**Comment by jlsjonas** [comment] 2022-01-23 19:01
> this would be an awesome function (temp conversion) to have natively in this card - is that possible?

That would be quite out of scope of this card, and only useful for very few people. A template sensor makes most sense if you need this.

@Tinkergnome621 could you confirm that the issue is resolved?

**Comment by ildar170975** [comment] 2022-02-11 17:38
The answers were given - wrong entity name was specified in the card.
No response from the topic starter.
Closed.

**Closed by ildar170975** 2022-02-11 17:38 UTC
Labels: More info needed
