### ISSUE TITLE
Rendering issue on Android 7.0

### ISSUE THREAD

**Issue by alexvillehart** [kalkih/mini-graph-card#477] opened 2020-10-20 02:03 UTC
I'm currently running a wall mounted Galaxy Tab S2 (9.7) running Android 7.0. When viewing from the Home Assistant android application (version 2.5.0-full) and from the browser, the graphs do not want to render properly
![image](https://user-images.githubusercontent.com/9193198/96530951-3e513780-1291-11eb-919f-0afb6a3677ad.png)

After doing some testing, without a fill attribute the graphs render properly inside a browser, but not within the app.

**Comment by Hypfer** [comment] 2020-10-24 11:30
Most likely caused by an outdated WebView component.

https://play.google.com/store/apps/details?id=com.google.android.webview

Try updating it

**Comment by RomRider** [comment] 2021-01-17 19:22
Did you manage to fix it by updating webview? If yes, please close the issue

**Comment by RomRider** [comment] 2021-01-20 01:38
Duplicate of #422

**Closed** 2021-01-20 01:39 UTC
Labels: bug, duplicate, wontfix
