### ISSUE TITLE
Secondary graph does not progress/refresh

### ISSUE THREAD

**Issue by mynameisdaniel32** [kalkih/mini-graph-card#200] opened 2019-11-06 22:37 UTC
When leaving a Lovelace window/tab open for a while, the primary graph seems to automatically progress/update correctly as time passes, however the secondary one does not. In the screenshot below the green dips should correspond with the red spikes, but as I had the page open for a few days they fell noticeably out of sync the next time I looked at them.

![image](https://user-images.githubusercontent.com/24840952/68343727-5b9efb80-013d-11ea-9e69-fda73685095b.png)

This is happening pretty consistently for me, I have a few dashboards which run all the time. If I manually refresh the page things line up again:

![image](https://user-images.githubusercontent.com/24840952/68343820-999c1f80-013d-11ea-8c0f-448bcbf0aa77.png)

Running the latest HACS version of the card and latest Home Assistant.

**Comment by tomlut** [comment] 2019-11-07 22:05
Same issue. https://github.com/kalkih/mini-graph-card/issues/194

I am using the secondary axis for the boolean.

**Comment by kalkih** [comment] 2019-11-08 13:33
Yes, most likely caused by the same issue.
Most likely caused by the way we handle graph updates, each entity has an individual graph and the graph is only updated once its entity is updated in HA, we should probably force update all graphs when any one entity is updated, this should ensure that they stay in sync.
We should also force update the graphs at least once every interval (`60` / `points_per_hour`)min to make sure the representation is accurate with the x-axis.

Could you try setting the `update_interval` option and see if that improves things? Set it to `60` or something, that should make the graphs re-render/update every 60sec.

**Comment by tomlut** [comment] 2019-11-08 16:26
I gave it a try but an update interval does not seem to help completely. It seems to slow down the lack of synchronisation but not eliminate it.

**Comment by kalkih** [comment] 2019-12-01 00:42
Please try the latest beta release [v0.9.0-beta](https://github.com/kalkih/mini-graph-card/releases/tag/v0.9.0-beta).

**Comment by tomlut** [comment] 2019-12-01 13:30
As per my misplaced comment in the other issue, I installed the beta and upgraded home assistant soon after (0.102.3) then did a Ctrl+Shift+R to reload but see no improvement with the misalignment with time. Should Ctrl+Shift+R be enough for this issue?

**Comment by kalkih** [comment] 2019-12-01 13:41
Alright!
Yes, clearing cache should not be necessary to solve this issue.
Are they still aligned correctly when you initially load the page?
Make sure you're not using the `update_interval` option as that will override the default graph updates now, should change that behaviour before release.

**Comment by tomlut** [comment] 2019-12-01 23:08
I removed `update_interval` from my graphs but the misalignment is still occurring with time. Yes they are aligned on initial page load or reload.

![Screenshot_2019-12-02 Home Assistant(1)](https://user-images.githubusercontent.com/10679300/69921946-85a0cf00-14eb-11ea-9ded-cbd2df9ec16b.png)

![Screenshot_2019-12-02 Home Assistant](https://user-images.githubusercontent.com/10679300/69921948-8a658300-14eb-11ea-979c-eb7ab191f070.png)

**Comment by mynameisdaniel32** [comment] 2019-12-02 00:17
Same here for me too on the 0.90 beta, with update_interval removed and the usual array of refreshing.

**Comment by kalkih** [comment] 2019-12-02 15:37
Okay!

With the changes made in https://github.com/kalkih/mini-graph-card/pull/214 all graphs are now recalculated on each update, which really should make them stay in sync 🤔
If we compare with before, an entity's graph would only be recalculated when there were new data coming from HACS, so if one entity in the graph didn't get updated in a while and another one did, it would result in them getting out of sync.

I did also add a minimum update frequency which ensures the graphs are recalculated at least once every `1 / points_per_hour` hour even if there's no new data coming from Home Assistant.

Are you sure your browsers are loading the new card version and not the old one from cache?
Check this https://github.com/kalkih/mini-graph-card/issues/169 issue if you've installed the card through HACS.
Please also try the setting `cache: false` so we can eliminate potential caching related issues, this setting will disable all caching of history data.

Thank you for sticking with me and helping me solve this issue, I'm trying my best but this proved to be trickier than I initially thought 😆

**Comment by kalkih** [comment] 2019-12-02 15:44
Here's a quick example with 0.9.0-beta showing the progression and sync of the graphs. hours_to_show is set ridiculously high in this example to display the effect.

![Kapture 2019-12-02 at 16 22 25](https://user-images.githubusercontent.com/457678/69972847-b4866780-1522-11ea-9ae1-f0818f1e389e.gif)

**Comment by mynameisdaniel32** [comment] 2019-12-03 03:14
Trying `cache: false` seems to have improved things for me. Will keep it running and see what happens.

**Comment by tomlut** [comment] 2019-12-03 03:35
>Are you sure your browsers are loading the new card version and not the old one from cache?
Check this #169 issue if you've installed the card through HACS.

Checked and my resource is correct as per that instruction.

I tried with a private browsing window (no cache). Still observing the issue.

Adding `cache: false` has not improved it.

**Comment by mynameisdaniel32** [comment] 2019-12-03 04:20
Just having a closer look at it, it seems existing plotted points are moving across okay for me, but it's not calculating new points and plotting them, it's just graphing the previous values (i.e. the right side of the graph is a flat line).

This is with the local caching off, a manual refresh fixes it.

**Comment by terminet85** [comment] 2019-12-08 16:31
> Just having a closer look at it, it seems existing plotted points are moving across okay for me, but it's not calculating new points and plotting them, it's just graphing the previous values (i.e. the right side of the graph is a flat line).
> 
> This is with the local caching off, a manual refresh fixes it.

Yes, reloading with empty cache will charge the correct data.

Waiting for a fix, thanks :)

**Comment by kalkih** [comment] 2020-01-29 15:22
I believe this should be fixed now with the latest release, give it a shot and feel free to re-open if you experience the issue persist.

**Closed by kalkih** 2020-01-29 15:22 UTC
Labels: bug
