### ISSUE TITLE
[FR] Display graphs in opposite Z-order: the last entity = bottommost, the 1st entity = topmost

### ISSUE THREAD

**Issue by jchhenderson** [kalkih/mini-graph-card#825] opened 2022-08-11 19:45 UTC
Hi,

It appears to me that the lines are drawn in the order of the entities listed.  This means the last entity is drawn over the others.  I would request that there is the capability to make the last entity listed (the top drawn one) to be the main entity shown (for state etc at the top of the card).

Hope this makes sense!

**Comment by ildar170975** [comment] 2022-08-12 11:01
Sorry, let me clarify.
Consider this example:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.mijia_300_1_temperature
    color: blue
    show_state: true
    name: Temp
  - entity: sensor.mijia_300_1_co2
    color: red
    show_state: true
    y_axis: secondary
    name: Humidity
```
![image](https://user-images.githubusercontent.com/71872483/184338723-e1e2b7fc-252c-479f-a3c2-89533954c65f.png)

Here "entity_1" state is on the left side.
If you add more entities - then 2nd, 3rd ... will be on the right side.
So, here entities are placed accordingly to their order (1st - left, others - in the right).

As for order of filling - unclear what color is on the top since colors are semi-transparent.
To know it - let's use [some card-mod](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2281) to remove transparency:
```
card_mod:
  style: |
    .fill {
      fill: white;
      opacity: 1 !important;
    }
```
which gives this:
![image](https://user-images.githubusercontent.com/71872483/184339312-ce472d1a-0458-47cb-a75f-ace061b95df9.png)
So, the order is same as above - but gives an opposite result.

Here we probably should display graphs in opposite order.
Agree?

**Comment by jchhenderson** [comment] 2022-08-12 11:33
Hi,

I am not sure what point you are trying to make.  Are you agreeing with my request or telling me it is not necessary or something else?

>If you add more entities - then 2nd, 3rd ... entities will be on the right side.

yes, if you specify `y_axis: secondary`
I am not using `y_axis: secondary` in my scenario

This is my min-graph
![Screenshot 2022-08-12 at 12 23 48](https://user-images.githubusercontent.com/34644672/184344497-567c191a-94ba-4871-bc73-71fb91a3a7f1.png)

I would like the coloured line (outside temp) to be drawn over the two black lines (highest inside, coolest inside).  I seem to be able to only do this by making it the 3rd entity, but then the 1st entity is the one shown in the top-left corner.

here is my yaml:
```
  - type: custom:mini-graph-card
    name: 'Outside'
    show:
      state: true
      name: true
      icon: false
      extrema: true
    height: 300
    entities:
      - entity: sensor.outside_temp
        state_adaptive_color: true
        show_fill: false
        name: Outside
        show_state: true
        show_points: true
        show_legend: false
      - entity: sensor.hottest_temp
        name: Hottest inside
        show_state: false
        show_fill: false
        color: var(--paper-card-background-color)
        show_points: false
        show_legend: false
      - entity: sensor.coolest_temp
        color: var(--paper-card-background-color)
        name: Coolest inside
        show_state: false
        show_fill: false
        show_points: false
        show_legend: false
    hour24: true
    hours_to_show: 48
    lower_bound: 12 #"{{ states('sensor.coolest_inside_temp_48_hrs') }}" # templates not supported
    upper_bound: 35 #"{{ states('sensor.hottest_inside_temp_48_hrs') }}" # templates not supported
    points_per_hour: 4
    color_thresholds:
      - value: -10
        color: '#000fff' # Blue
      - from: 3
        color: '#002aff' # Blue (RYB)
      - color: '#055fff' # Blye (RYB)

      [...]
```

..._what I really want to do_ is show the difference between the two lines as a fill.

From what I read of your reply, if I put the lines on `y_axis: secondary`, fill them, make one the colour of the card background and set transparency to ), I could do this??  ...I'm going to try that now....

**Comment by jchhenderson** [comment] 2022-08-12 11:43
Hi,

I modified entities 2 and 3 as follows and also set upper/lower boundaries for the y axis.  I cannot get card_mod to remove the transparency of the last sensor.  I have never used card_mod before.  can you tell me where I am going wrong?

```
      - entity: sensor.hottest_temp
        name: Hottest inside
        y_axis: secondary
        show_state: false
        #show_fill: false
        show_line: false
        color: grey
        show_points: false
        show_legend: false
      - entity: sensor.coolest_temp
        card_mod:
          style: |
            .fill {
              fill: white;
              opacity: 1 !important;
            }
        color: var(--paper-card-background-color)
        name: Coolest inside
        y_axis: secondary
        show_state: false
        #show_fill: false
        show_line: false
        show_points: false
        show_legend: false
        card_mod:
          style: |
            .fill {
              fill: white;
              opacity: 1 !important;
            }

```

gives me almost what I am really looking for (just need the lower fill to be not transparent).
![Screenshot 2022-08-12 at 12 42 53](https://user-images.githubusercontent.com/34644672/184347205-690b662c-cace-473e-8007-65e66a307cca.png)

**Comment by ildar170975** [comment] 2022-08-12 11:45
> Are you agreeing with my request or telling me it is not necessary or something else?

Repeat:
- "let me clarify."
- "Here we probably should display graphs in opposite order.
Agree?"
Sorry - what is unclear?

> yes, if you specify `y_axis: secondary`

This is not important.
Used to make graphs absolutely different to see the issue. Many lines in your example are not related to the issue.

> here is my yaml:

Please provide SHORT code snippets.

**Comment by jchhenderson** [comment] 2022-08-12 11:46
got it on both comments - thanks and sorry, respectfully.

**Comment by ildar170975** [comment] 2022-08-12 11:48
To conclude - are you agree that we inly need to change an order of displaying graphs?
I mean:
4th entity -> then 3rd entity -> then 2nd entity -> then 1st entity
?

**Comment by jchhenderson** [comment] 2022-08-12 11:51
yes, that is what I meant - sorry I was not clear and sorry I did not understand your reply properly the first time.

**Comment by ildar170975** [comment] 2022-08-12 12:01
@jchhenderson 
1. Renamed the issue to specify our conclusion.
2. For card-mod questions - please [check here](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1396) for a list of examples for mini-graph-card.
3. There was an issue or even a PR here to price a kind of "index" option for each entity - and this option was supposed to be used to specify an order. I dislike this proposal, honestly.

**Comment by ildar170975** [comment] 2022-09-15 02:20
Noted that this issue is a duplicate of https://github.com/kalkih/mini-graph-card/issues/269#issuecomment-1247376453
Closing it.

**Closed by ildar170975** 2022-09-15 02:20 UTC
Labels: enhancement
