### ISSUE TITLE
Chrome Issue with Non-Numeric Sensor, works in other browsers

### ISSUE THREAD

**Issue by kendrome** [kalkih/mini-graph-card#410] opened 2020-07-29 22:23 UTC
I have the following basic card
```
  - type: custom:mini-graph-card
    hours_to_show: 168
    state_map:
      - value: "above_horizon"
        label: Day
      - value: "below_horizon"
        label: Night
    entities:
      - entity: sun.sun 
```
This works in Firefox, Edge, Safari and the official Android Home Assistant App, but does not work in Chrome on desktop or mobile.
Chrome:
![image](https://user-images.githubusercontent.com/4109239/88859693-d7efd800-d1bf-11ea-9d28-6dc20552382f.png)
Other:
![image](https://user-images.githubusercontent.com/4109239/88859729-ee962f00-d1bf-11ea-8eae-34d158210174.png)

**Comment by kalkih** [comment] 2020-09-02 06:35
The state_map option doesn't respond well to caching & changes made to the card configuration, so if you played around with the config in chrome before you set the "final" state_map there could be cached data that's incompatible, try setting `cache: false` on the card or if you still want it to cache data, force clear the cache by changing `hours_to_show` -> open the HA page with the card -> change hours_to_show back -> load the page once again.

**Comment by RomRider** [comment] 2021-01-20 01:41
Duplicate of #505

**Closed** 2021-01-20 01:41 UTC
Labels: bug, duplicate
