### ISSUE TITLE
Uncaught TypeError: Cannot add property index, object is not extensible

### ISSUE THREAD

**Issue by vaidyasr** [kalkih/mini-graph-card#293] opened 2020-03-06 03:08 UTC
After updating 0.106.5 I am not able to use mini-graph-card at all. I got the error at console and the UI is blank.
```
mini-graph-card-bundle.js:1 Uncaught TypeError: Cannot add property index, object is not extensible
    at mini-graph-card-bundle.js:1
    at Array.forEach (<anonymous>)
    at HTMLElement.set hass [as hass] (mini-graph-card-bundle.js:1)
    at HTMLElement._createCardElement (hui-stack-card.ts:79)
    at HTMLElement._rebuildCard (hui-stack-card.ts:96)
    at HTMLElement.<anonymous> (hui-stack-card.ts:85)
    at r (fire_event.ts:76)
    at create-element-base.ts:94
```

**Comment by kalkih** [comment] 2020-03-06 07:32
Please, try looking for existing issues before opening new ones.
Duplicate of #274, #275, #284, #285, #286, #287, #290 

> This has been fixed in the latest version of the card released a few days back.
> 
> If you still have the issue after updating the card that means your browser isn't loading the updated version of the card. Try the following:
> 
> * Reinstall the card in HACS (if installed though HACS)
> * Double check the resource reference (if installed though HACS), make sure it match the one in HACS #169
> * Clear browser cache
> 
> If you still have issues after this, open the browser developer console (google how to do this) and look for a line which says "MINI-GRAPH-CARD" followed by the version number and let me know what version it says.

**Closed by kalkih** 2020-03-06 07:32 UTC
Labels: duplicate

**Comment by vaidyasr** [comment] 2020-03-06 07:47
The version it says is  MINI-GRAPH-CARD  0.9.3

**Comment by vaidyasr** [comment] 2020-03-06 07:48
Tried clearing cache and even loaded through incognito mode. Still same error
