### ISSUE TITLE
Feature request: Scale input

### ISSUE THREAD

**Issue by wormiedk** [kalkih/mini-graph-card#535] opened 2021-01-14 09:25 UTC
It would be great if there was a possibility of scaling the input so I could have more graphs sharing the same axis. 

As an example I have a radiator with a status variable between 0 and 3 that I would like to display alongside another value which is in the range of 0-100. It would be great if I could multiply the status variable by e.g 20 in order to display them together on the same axis.

I am already using the other axis for something different.

**Comment by RomRider** [comment] 2021-01-18 20:49
Well, that doesn't look very logic for a graph. An axis represents a type of value with a defined scale, it can't represent 2 different scales at the same time on the same axis. Sounds like comparing apples and oranges.

You could however create a template sensor in home assistant which would multiply the value by 20 and display that sensor in the graph instead.

**Comment by ildar170975** [comment] 2022-02-11 17:16
1. The `value_factor` is introduced in v0.9.4.
2. The `value_factor` should be per-entity - https://github.com/kalkih/mini-graph-card/issues/607
3. The `value_factor` should be [-xxx.xxx, +xxx.xxx] - see https://github.com/kalkih/mini-graph-card/issues/591

Closed as duplicate in favour of https://github.com/kalkih/mini-graph-card/issues/591

**Closed by ildar170975** 2022-02-11 17:16 UTC
Labels: duplicate

**Comment by andrewjswan** [comment] 2022-02-14 11:21
Or for graph like:
![image](https://user-images.githubusercontent.com/3609660/153855040-92220157-c41d-415c-8eab-4ea00c932bb2.png)

**Comment by ildar170975** [comment] 2022-02-14 12:08
The issue is closed.
Add new ideas into open related issues.
