### ISSUE TITLE
doesn't work in android app (custom element doesnt' exist: mini-graph-card)

### ISSUE THREAD

**Issue by schel4ok** [kalkih/mini-graph-card#496] opened 2020-11-21 20:52 UTC
it works on PC version, but when I check in mobile app I just see following error
![photo_2020-11-21_23-52-05](https://user-images.githubusercontent.com/10367464/99887343-985c6880-2c54-11eb-84e8-7592198d3889.jpg)

**Comment by benjgos** [comment] 2020-12-02 04:02
not sure if this is valid for the android app, but try clicking on the ... on the top right and select Reload Resources.

**Comment by Dave-Casey** [comment] 2020-12-03 20:55
I can confirm that I see the same issue in Fully Kiosk Browser running on a Amazon Fire HD8 (Android)

**Comment by MJPVDH** [comment] 2020-12-06 17:07
Same error for me on Samsung Note 9 with Home Assistant app.

**Comment by RomRider** [comment] 2021-01-18 20:58
I'm not sure this card works on amazon Fire (I think Amazon tablets have some limitations).
However, for all the others, your resource is probably not properly setup in Home Assistant.

Please tell use how you installed mini-graph-card and what your resources config looks like.

**Comment by JanGonet** [comment] 2021-01-20 00:17
Same error for me on Samsung Galaxy Tab 4 running Android 4.4, however it works correcly on Xiaomi Mi10T Pro running Android 10.

**Comment by RomRider** [comment] 2021-01-20 10:33
It is definitely with your android version. 4.4 is 10 years old... If you can, update your webview. If not, sorry, we can't support old browser versions forever :(

**Comment by DKCroCo** [comment] 2021-05-01 13:33
I have the same issue on iOS 14 app

**Comment by Williokeef** [comment] 2021-06-05 06:09
> 
> 
> it works on PC version, but when I check in mobile app I just see following error
> ![photo_2020-11-21_23-52-05](https://user-images.githubusercontent.com/10367464/99887343-985c6880-2c54-11eb-84e8-7592198d3889.jpg)

Just had a similar issue on my samsung note 20. Try clearing both Data and Cache for the HA app. Custom card shows up now.

**Comment by hannta** [comment] 2021-07-25 20:26
I had same issue, onplus 8t (android 11).

Clearing app data & cache did not help.

**Comment by jlsjonas** [comment] 2022-01-15 15:04
Closing as the original issue has been _resolved_; if you're seeing this error, please make sure the card is actually properly installed **and you have restarted HA (core)**

If you verified it's only broken on a specific device, and you have ensured it's not a caching issue, please create a new issue.

**Closed by jlsjonas** 2022-01-15 15:04 UTC
Labels: question

**Comment by sEdsKi** [comment] 2022-01-23 01:38
I had this issue and resolved it by removing any text after .js
<img width="497" alt="image" src="https://user-images.githubusercontent.com/98076159/150661240-26033b80-be9f-42ee-8574-972a682a7dc0.png">

**Comment by jlsjonas** [comment] 2022-01-23 05:12
You effectively cleared the file's cache by doing that; not sure if that's a bug on our side... (the number is there to provide a unique identifier)

**Comment by ForcedNative** [comment] 2023-05-09 21:56
> 

Worked for me as well

**Comment by ms-mer** [comment] 2023-06-07 16:54
Worked for me on an Amazon Tablet, thanks
