### ISSUE TITLE
Times: 24:xx should be 00:xx

### ISSUE THREAD

**Issue by brunohaller** [kalkih/mini-graph-card#560] opened 2021-02-11 10:00 UTC
When using a 24h scheme like in most parts of the world, times in the hour after midnight are shown as 24:xx, but that does not exist, it should be 00:00 to 00:59

![image](https://user-images.githubusercontent.com/73822257/107622516-3fe7a680-6c58-11eb-84d2-2bc9443c475c.png)

**Comment by RomRider** [comment] 2021-02-11 11:30
This is already fixed in the latest beta.

**Comment by RomRider** [comment] 2021-02-11 11:30
Duplicate of #536

**Closed by RomRider** 2021-02-11 11:30 UTC
