### ISSUE TITLE
[Feature request] reference value

### ISSUE THREAD

**Issue by barbatrukko** [kalkih/mini-graph-card#584] opened 2021-03-23 16:37 UTC
Is it possible to display a reference value?
For example, if I visualize the curve of two temperatures oscillating around a range, I would like to be able to see a constant line, for example at 21 ° to relate the trend of the curves with respect to the reference value.
I would therefore like to add a constant value that generates a horizontal line/threshold.

**Comment by lanrat** [comment] 2021-06-03 21:53
Is this the same as #570?

**Comment by RomRider** [comment] 2021-06-03 22:02
Duplicate of #570

**Closed by RomRider** 2021-06-03 22:02 UTC
