### ISSUE TITLE
feature request: add decimals to Entities object

### ISSUE THREAD

**Issue by michapr** [kalkih/mini-graph-card#751] opened 2022-03-05 17:24 UTC
Would it be possible to add the 'decimals' to 'Entities object'?

As sample it make sense to show in card the temperature with decimals, but humidity without.

Thanks!

**Comment by ildar170975** [comment] 2022-03-05 20:57
Duplicate of https://github.com/kalkih/mini-graph-card/issues/685

**Closed by ildar170975** 2022-03-05 20:57 UTC
Labels: duplicate
