### ISSUE TITLE
Setting for , and . or nothing

### ISSUE THREAD

**Issue by DSDV** [kalkih/mini-graph-card#810] opened 2022-07-09 16:22 UTC
Hi, 

first of: thank you for this great card it is really beautiful and i already use it 3 times <3
though i tried several hours to mix a "sensor mistake" which i found out is none ^^
card shows , and . the other way around (which i guess is how America does it?). 

**i would love a setting for getting one thousand as 1 000,00 or 1.000,00
the current default 1,000.00 is very misleading in my country :(**

with kind regards

PS: home assistant seems to chose this automatically since the same sensor as single entity is shown "correctly"
![image](https://user-images.githubusercontent.com/5504857/178114364-6501e388-3cc1-4c99-951d-124dc3da1db8.png)

**Comment by ildar170975** [comment] 2022-07-09 17:31
1. Next time please be more specific when defining a title for an issue.
2. Duplicate of https://github.com/kalkih/mini-graph-card/issues/702

**Closed by ildar170975** 2022-07-09 17:31 UTC
Labels: duplicate

**Comment by ildar170975** [comment] 2022-07-09 22:48
And please do not rename the issue to duplicate (as well as cleaning the issue's content).

**Comment by DSDV** [comment] 2022-07-10 07:12
sorry was trying to delete it but i didnt finde the option/button to do so
