### ISSUE TITLE
Error "Cannot assign to read only property '0' of object '[object Array]'"

### ISSUE THREAD

**Issue by balajeek** [kalkih/mini-graph-card#290] opened 2020-03-01 02:42 UTC
I am using many mini-graph cards in my HASS (ver 0.106.2) and it stopped working 2 days ago with the error message mentioned.  I haven't touched anything for a while so I am not sure what happen.  I went to community and noticed mini-graph card had an update  (0.9.3) so i took the update hoping that will fix, but not.  

any idea?

**Comment by balajeek** [comment] 2020-03-01 02:59
just a screenshot of one of them here..

![Screen Shot 2020-02-29 at 9 58 09 PM](https://user-images.githubusercontent.com/19213088/75618587-a0143400-5b3e-11ea-893f-b82374f4d956.png)

**Comment by carlos-sarmiento** [comment] 2020-03-01 08:15
I'm having the same error.
Here is my card configuration
```
    - type: custom:mini-graph-card
        line_width: 2
        name: "Days Remaining"
        points_per_hour: "1"
        icon: "fal:calendar"
        hours_to_show: "1"
        unit: days
        line_color: "var(--p367c)"
        update_interval: 5
        aggregate_func: "max"
        entities:
          - sensor.dry_age_60d_days
        show:
          labels: no
          points: no
          graph: no
```

**Comment by kalkih** [comment] 2020-03-01 09:28
Please, try looking for existing issues before opening new ones.
Duplicate of #274, #275, #284, #285, #286, #287

> This has been fixed in the latest version of the card released a few days back.
> 
> If you still have the issue after updating the card that means your browser isn't loading the updated version of the card. Try the following:
> 
> * Reinstall the card in HACS (if installed though HACS)
> * Double check the resource reference (if installed though HACS), make sure it match the one in HACS #169
> * Clear browser cache
> 
> If you still have issues after this, open the browser developer console (google how to do this) and look for a line which says "MINI-GRAPH-CARD" followed by the version number and let me know what version it says.

**Closed by kalkih** 2020-03-01 09:28 UTC
Labels: duplicate
