### ISSUE TITLE
Feature request: Gridlines

### ISSUE THREAD

**Issue by torkelsson** [kalkih/mini-graph-card#132] opened 2019-08-09 06:33 UTC
As far as I understand there are no obvious way to create gridlines in the graphs. For instance in temperature graphs I'm interested in having gridlines every fifth grade and at midnight every day, just to be able to get a quick view about the temperature at a certain time. If I want the exact temperature and time I can hover over the graph.

**Comment by kalkih** [comment] 2019-08-11 11:13
Duplicate of #21

**Closed by kalkih** 2019-08-11 11:13 UTC
Labels: duplicate
