### ISSUE TITLE
[Functionality Missing] How to show X-axis values?

### ISSUE THREAD

**Issue by embcla** [kalkih/mini-graph-card#472] opened 2020-10-12 14:20 UTC
So I'm trying to show x-axis values like so
<img width="564" alt="hours graph" src="https://user-images.githubusercontent.com/54371771/95757030-e28e1980-0ca6-11eb-95c6-d3cf5f427a4b.PNG">

is there a way to achieve this?

**Comment by gh0st125** [comment] 2020-11-04 10:49
I also want this feature. What's the point of a graph when there's no indicator for the unit of measurement?

**Comment by der1igedon** [comment] 2021-01-05 08:44
me too! that would be great!
and some formatting options for the y-axis would be necessary as well.

**Comment by JJFourie** [comment] 2021-01-10 15:50
Yep, would be terribly nice. Including the grid lines, of course.

On the topic, what about the Y-Axis? 
From what I currently see, and maybe I miss something, the y-axis labels when shown are only the Min and Max values, without the option to add anything in between. And there are also no option to show grid lines, which means the graph is largely "floating" without a real (visual) reference of where it sits with respect to the measuring scale.

**Comment by RomRider** [comment] 2021-01-17 19:35
Duplicate of #21 (let's discuss it there while I'm trying to wrap my head around the codebase :))

**Comment by RomRider** [comment] 2021-01-17 19:36
Duplicate of #21
(let's discuss it there while I'm trying to wrap my head around the codebase :))

**Closed by RomRider** 2021-01-17 19:35 UTC
