### ISSUE TITLE
Feature Request: align state within header

### ISSUE THREAD

**Issue by kalhimeo** [kalkih/mini-graph-card#494] opened 2020-11-16 01:25 UTC
Hi,

Your lovelace card is fantastic, thank you so much for the great work.

My small suggestion would be to have an option to align the state within the header row (with name and icon). Exemple :

![image](https://user-images.githubusercontent.com/6355373/99203416-d0762e00-27b2-11eb-9b70-ddf9469ff5d0.png)

Thank you very much in advance !

**Comment by RomRider** [comment] 2021-01-19 23:10
Duplicate of #157

**Closed** 2021-01-19 23:10 UTC
Labels: feature request
