### ISSUE TITLE
Updating from 0.3.0 to 0.6.0 fill no longer matching current line color_threshold definition

### ISSUE THREAD

**Issue by peterhoe** [kalkih/mini-graph-card#150] opened 2019-09-07 23:04 UTC
Expected Output as follows using 0.3.0 “mini-graph-card-bundle.js”Output as follows using 0.3.0 “mini-graph-card-bundle.js”

![0 3 0-graph](https://user-images.githubusercontent.com/36558013/64480956-2bf37600-d216-11e9-8df2-ff181591e34d.png)

Output using 0.6.0 “mini-graph-card-bundle.js”

![0 6 0-graph](https://user-images.githubusercontent.com/36558013/64480959-3dd51900-d216-11e9-972b-93f0ac34893f.png)

Have tried amending show fill to true / false / fade, has not resolved. Also cleared cache during each change.  Seems to work fine with 0.3.0.
In Ver 0.6.0 Fill always filling with same color regardless of line color.  In version 0.3.0 fill would always display according to line color display as defined under color_thresholds

Entity definition as follows in ui-lovelace.yaml

`# mini graph card #
# Spend Earn #
          - type: custom:mini-graph-card
            name: Elec $ 36Hr inc 3.5c phr conn 1Hr Avg
            icon: mdi:currency-usd
            entities:
              - entity: sensor.elecspendearn60minaverage
                name: Elec Spend Hr Avg
            hours_to_show: 36
            points_per_hour: 30
            hour24: true
            height: 390
            line_width: 3
            line_color:
              - "#0ff"
            more_info: false
            show:
              labels: true
              fill: true
            color_thresholds:
              - value: 90
                color: "#f00"
              - value: 70
                color: "#f03"
              - value: 60
                color: "#f06"
              - value: 50
                color: "#f08"
              - value: 40
                color: "#d0f"
              - value: 30
                color: "#fa0"
              - value: 25
                color: "#fb0"
              - value: 20
                color: "#fc0"
              - value: 17
                color: "#fd0"
              - value: 15
                color: "#fe0"
              - value: 13
                color: "#ff0"
              - value: 11
                color: "#ef0"
              - value: 9
                color: "#0af"
              - value: 7
                color: "#0cf"
              - value: 1
                color: "#0ff"
              - value: -1
                color: "#0a0"
              - value: -3
                color: "#0b0"
              - value: -5
                color: "#0c0"
              - value: -7
                color: "#0d0"
              - value: -9
                color: "#0e0"
              - value: -33
                color: "#0f0"`

**Comment by kalkih** [comment] 2019-09-07 23:13
Hey, thanks for the report, this is duplicate of https://github.com/kalkih/mini-graph-card/issues/146 so I'll close this one.

Will be fixed in the next release where the fill will follow the gradients of the color thresholds (same as the line) https://github.com/kalkih/mini-graph-card/commit/e2a0fa5da0977163081a3554758e6b012a82d27a as suggested in https://github.com/kalkih/mini-graph-card/issues/112.

**Closed by kalkih** 2019-09-07 23:13 UTC
