### ISSUE TITLE
Wrong last bar value - always zero.

### ISSUE THREAD

**Issue by dzikus** [kalkih/mini-graph-card#289] opened 2020-02-29 17:38 UTC
Last bar on graph is wrong, also hours to show omitting last day (history-graph show one day more with 720 hours).

![image](https://user-images.githubusercontent.com/3209066/75612285-54539180-5b22-11ea-885b-a9dbc7c0b1a3.png)
![image](https://user-images.githubusercontent.com/3209066/75612286-57e71880-5b22-11ea-8ff8-0269a343a715.png)
￼
```yaml
aggregate_func: max
cache: false
color_thresholds:
  - color: '#f0f042'
    value: 15
  - color: '#f0e342'
    value: 7.5
  - color: '#d0c442'
    value: 5
  - color: '#c0c042'
    value: 0
entities:
  - entity: sensor.daily_pv4
    index: 0
    name: Dzienna produkcja PV
group_by: date
hours_to_show: 720
icon: 'mdi:solar-power'
show:
  graph: bar
type: 'custom:mini-graph-card'
```

```yaml
entities:
  - entity: sensor.daily_pv4
hours_to_show: 720
refresh_interval: 0
type: history-graph
```

**Comment by kalkih** [comment] 2020-02-29 21:46
Group by date will often show one less day than the history graph since using "group_by: date" will only display whole days compared to history graph where the first entry will be current time of day 720h. With mini-graph-card you'll get end of current day (00:00) - 720h.

I need more information than "last bar in graph is wrong", I can't really do anything with that information.

**Comment by dzikus** [comment] 2020-03-01 10:51
It is showing 0, but there is 2.3 value as I show on history-graph card. Bellow again there is 248 max value on history-graph but on mini-graph-card there is zero 0.


<img width="344" alt="Zrzut ekranu 2020-03-1 o 11 43 54" src="https://user-images.githubusercontent.com/3209066/75624136-f078a980-5bb1-11ea-93dd-e601bf648b5a.png">
<img width="342" alt="Zrzut ekranu 2020-03-1 o 11 47 38" src="https://user-images.githubusercontent.com/3209066/75624196-78f74a00-5bb2-11ea-93d7-3fbc439c8750.png">

```yaml
aggregate_func: max
cache: false
entities:
  - color: '#0399ff'
    entity: sensor.daily_water
    index: 0
    name: Example of last bar with 0 value
group_by: date
hours_to_show: 168
icon: 'mdi:water-pump'
show:
  graph: bar
type: 'custom:mini-graph-card'
```

On my every bar graph last bar is 0:
<img width="341" alt="Zrzut ekranu 2020-03-1 o 11 42 55" src="https://user-images.githubusercontent.com/3209066/75624145-01291f80-5bb2-11ea-98b1-c011f213b8ba.png">
<img width="343" alt="Zrzut ekranu 2020-03-1 o 11 42 39" src="https://user-images.githubusercontent.com/3209066/75624150-06866a00-5bb2-11ea-90f2-8855968f0054.png">

**Comment by reaper7** [comment] 2020-03-02 06:51
I have the same, oldest day is always show as zero.
Eg.
168 hours, as You see most left blue value (tuesday) show 0.
Please note too on the marked value from Sunday (dirty yellow) which shows 5,28kWh
![168](https://user-images.githubusercontent.com/4134851/75651956-2d987680-5c5a-11ea-9b4f-444eaab35429.jpg)

but when I reduce the period to 48 hours, the most to the left will be Sunday
![48](https://user-images.githubusercontent.com/4134851/75652035-60426f00-5c5a-11ea-98bb-97a10b486bfb.jpg)
which shows now the 0 value

**Comment by kalkih** [comment] 2020-03-04 20:08
What card version are you two on?
Open the browser developer console and look for the `mini-graph-card` version in the log.

**Comment by reaper7** [comment] 2020-03-04 20:22
0.9.3

**Comment by kalkih** [comment] 2020-03-04 21:09
Does it say that in the developer log as well? Or is that what's shown in HACS?

**Comment by reaper7** [comment] 2020-03-04 21:31
HACS only,
developer console log shows nothing about mini-graph-card (I have a logger set to error only)

but /home/pi/.homeassistant/www/community/mini-graph-card/mini-graph-card-bundle.js contains inside:
```
console.info("%c MINI-GRAPH-CARD %c 0.9.3 "
```

**Comment by dzikus** [comment] 2020-03-05 10:08
0.9.3
I'm using virtual env HA with manually installed mini-graph-card.

<img width="537" alt="Zrzut ekranu 2020-03-5 o 11 04 57" src="https://user-images.githubusercontent.com/3209066/75970956-642bf680-5ed1-11ea-9ff7-fb954f3e4f0d.png">

**Comment by kalkih** [comment] 2020-03-05 17:54
> HACS only,
> developer console log shows nothing about mini-graph-card (I have a logger set to error only)

If the console doesn't show any mini-graph-card version that probably means your browser is loading a version prior to 0.9.0 (logging of version introduced). There could be several reasons for this, the browser could be loading an earlier version from cache, the resource url might be incorrect, make sure it match the one stated in HACS, e.t.c.



> 0.9.3
> I'm using virtual env HA with manually installed mini-graph-card.
> 
> <img alt="Zrzut ekranu 2020-03-5 o 11 04 57" width="537" src="https://user-images.githubusercontent.com/3209066/75970956-642bf680-5ed1-11ea-9ff7-fb954f3e4f0d.png">

Okay, does the issue persist if you set the option `cache: false`.
I'll try to reproduce it.

**Comment by reaper7** [comment] 2020-03-05 18:27
@kalkih - I didn't read that it was about the browser console ;)
I was looking for this in the HA dev console :)

Browser console show 0.9.3 :) 
I also have set cache: false

![dev_console](https://user-images.githubusercontent.com/4134851/76012865-4aad9d80-5f17-11ea-94e7-89091d8fbbee.jpg)

**Comment by dzikus** [comment] 2020-03-07 07:57
> Okay, does the issue persist if you set the option `cache: false`.

Yes.

**Comment by Vedeneb** [comment] 2020-03-12 19:21
I have exactly the same issue. Any news on this?
![image](https://user-images.githubusercontent.com/39202639/76559149-e18dd300-649e-11ea-905a-83ff94629c78.png)
Everything looks fine, except for the last bar which is always zero. I'm also using Version 0.9.3

**Comment by kmlucy** [comment] 2020-04-09 13:10
I have the same issue. If I add 24 hours, the day that was zero is now correct, but the last bar is still 0:
![image](https://user-images.githubusercontent.com/13952475/78898499-e44dfa80-7a41-11ea-8140-2c67f1fe4b2c.png)


![image](https://user-images.githubusercontent.com/13952475/78898447-d304ee00-7a41-11ea-984b-5860d4775701.png)

**Comment by maxwroc** [comment] 2020-04-09 21:53
I have sent a fix for this as it was bugging me for a while too :)

**Closed** 2020-04-13 13:25 UTC
Labels: bug

**Comment by reaper7** [comment] 2020-04-13 19:07
so, we waiting for new release for testing :)

**Comment by kmlucy** [comment] 2020-04-29 15:08
@kalkih Could we get a release so we can implement the fix?

**Comment by maxwroc** [comment] 2020-04-29 15:20
@kalkih please remember to update the version (logged in console) as I have forgotten to do it

**Comment by majdzik84** [comment] 2020-06-19 19:19
I still have this problem. Is this fixed? 0.93 and HA 0.111.4 

![image](https://user-images.githubusercontent.com/31352476/85172958-7bb9a000-b272-11ea-8cc7-4d7b31014126.png)

**Comment by maxwroc** [comment] 2020-06-19 19:36
No, you need to wait for the next release - after v0.9.3. Maybe @kalkih is holding on and wants to collect more features for release v1.0.0 ;)

**Comment by reaper7** [comment] 2020-07-03 06:40
@kalkih - is it possible to make a beta version? (if the official release is not ready yet)

**Comment by kalkih** [comment] 2020-07-03 07:31
Okay, will make a release tonight 🙃

**Comment by kalkih** [comment] 2020-07-03 20:49
Out now ➡️   [v0.9.4](https://github.com/kalkih/mini-graph-card/releases/tag/v0.9.4)
