### ISSUE TITLE
MIN and AVG are wrongly (?) calculated for group by date graphs

### ISSUE THREAD

**Issue by stefan-wimt** [kalkih/mini-graph-card#648] opened 2021-09-13 19:08 UTC
When aggregating by MAX and using group by date, I would expect the MIN and AVG values to be based on the grouped values (ie the average MAX value across multiple days and not the average overall value). See the image below, MIN should be 12.5kWh and AVG somewhere around 15/16 kWh.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/62101126/133141849-9db7d91e-3c34-4178-9761-47ed3473ffd2.png">

**Comment by jlsjonas** [comment] 2022-01-28 17:14
Duplicate of #618

**Closed by jlsjonas** 2022-01-28 17:14 UTC
Labels: bug, enhancement
