### ISSUE TITLE
color thresholds per entity

### ISSUE THREAD

**Issue by martijnz43** [kalkih/mini-graph-card#589] opened 2021-04-10 09:16 UTC
First I would like to say that it is a very nice graph card! I'm sorry if it's not the right location for the post.

Does anybody know if it's possible to use the color_thresholds option per entity when using different entities in one graph?

**Comment by mattbruman** [comment] 2021-06-17 23:13
I would like to second this question.

**Comment by RomRider** [comment] 2021-06-18 05:33
Apexcharts-card has this feature if you want to give it a try. 
This card is in maintenance mode and won't get new features.

**Comment by smizles** [comment] 2021-06-26 06:45
According to this 2019 comment, this should already be possible..? I'm testing now.

https://github.com/kalkih/mini-graph-card/issues/141#issuecomment-524989448

**Comment by jlsjonas** [comment] 2022-01-23 03:07
Duplicate of #153

**Closed by jlsjonas** 2022-01-23 03:07 UTC
Labels: enhancement, apexcharts-card
