### ISSUE TITLE
Min value wrongly calculated

### ISSUE THREAD

**Issue by mviklicky** [kalkih/mini-graph-card#582] opened 2021-03-23 06:33 UTC
Hello, at first, thank you for this lovelace resource!

But I got strange Min value from my temperature sensor.
Card is showing -3,32 degrees as a min value from Monday.
I checked the history of this sensor and there are two moments where it barely "touched" 0 degrees.

I am sending picure of card showing that value, history of that sensor and card configuration.

Am I doing something wrong? Or the calculation is wrong?

![mini-graph-card-strange-function-result](https://user-images.githubusercontent.com/29466170/112102942-5105ca80-8ba9-11eb-839c-850f207a4b81.png)

**Comment by jaimevisser** [comment] 2021-06-02 12:25
Duplicate of #567

**Closed** 2021-09-24 17:22 UTC
Labels: duplicate
