### ISSUE TITLE
[Feature Request] Capture Min/Max values for a 'month' rather than just number of hours/days

### ISSUE THREAD

**Issue by Joshndroid** [kalkih/mini-graph-card#930] opened 2023-02-22 09:48 UTC
Wondering if we can get a method of tracking a value over a month's length?
This would work well for tracking electricity usage, temperature, etc where a blanket number of hours is valid to a point but if your trying to track something like 'hottest day of the month, coldest day of the month' or 'day of the month where used the most electricity'
With months changing length a blanket 30 days also wouldn't work.

**Comment by ildar170975** [comment] 2023-02-22 20:44
There is a FR for supporting templates for card options.
If this support is added, then a simple template may be used for `hours_to_show` to define a month (for instance, like “from the 1st day of the current month till now”). 
A similar method was proposed earlier to define a “from 00:00 till now” interval. 
If you are interested in such implementation - please find that mentioned FR and start monitoring it, and this new issue may be closed then.

**Comment by ildar170975** [comment] 2024-01-19 19:36
Duplicate of https://github.com/kalkih/mini-graph-card/issues/1013

**Closed by ildar170975** 2024-01-19 19:36 UTC
Labels: duplicate
