### ISSUE TITLE
Processing of 'unavailable' values: displaying gaps

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#678] opened 2021-12-29 10:59 UTC
Is it possible to display gaps for periods where the sensor is `unavailable` ?

Look at these conventional graphs:
![изображение](https://user-images.githubusercontent.com/71872483/147655504-53fbba4e-cbc1-4735-9dc8-aa8113944962.png)
They have gaps for these periods.

**Comment by jlsjonas** [comment] 2022-01-16 08:53
Duplicate of #414

**Closed by jlsjonas** 2022-01-16 08:53 UTC
