### ISSUE TITLE
Bar chart continues with previous value if currently no value is available

### ISSUE THREAD

**Issue by eloo** [kalkih/mini-graph-card#481] opened 2020-10-28 07:46 UTC
Hi,

i'm currently creating a bar graph with daily metrics. 
So one bar per day with the last value. But some value are not available at the start of the day..
I would expect that the bar chart then does not show any bar for this day till the value is available. 
But sadly it just copies the previous value for the chart. In the legend i see NaN as expected.

Here is my graph card 
```
type: 'custom:mini-graph-card'
entities:
  - sensor.daily_sensor
name: Daily_sensor
hours_to_show: 240
aggregate_func: last
lower_bound: 0
upper_bound: 200
hour24: true
icon: none
show:
  labels: false
  graph: bar
group_by: date
color_thresholds:
  - value: 0
    color: '#32CD32'
  - value: 35
    color: '#FFD700'
  - value: 50
    color: '#FF0000'
  - value: 100
    color: '#660000'
```
![image](https://user-images.githubusercontent.com/2631895/97406855-236a6d00-18fa-11eb-8b82-e9e1a6961f90.png)

Also i hover over the current bar (where no value is available) it shows the value of the day before
![image](https://user-images.githubusercontent.com/2631895/97406947-439a2c00-18fa-11eb-94ff-a3ac1abd4613.png)

Do you have any ideas how i can make the graph not showing a bar if the value is not yet available?

Thanks

**Comment by kalkih** [comment] 2020-10-28 15:30
Hello, the problem here is that there's no way of knowing what the missing value should be parsed as.
When a normal sensor reports states such as unavailable e.t.c. we have to make a "guess" what the current value is and the best guess is usually to grab the latest previously known value, this works fairly well in most cases imo.

I'm not sure what state your `sensor.daily_sensor` resets to / reports at the start of the day, but it should in my opinion reset to `0` at the beginning of the day, that should solve your issues.
Perhaps you could adjust your template sensor or how it's set up, or perhaps look at setting up a [utility_meter](https://www.home-assistant.io/integrations/utility_meter/).

**Comment by eloo** [comment] 2020-10-28 15:43
Hi,

ah okay.. i see the problem. 
The problem here is that if i set it to 0 its not correct.. because 0 would be a valid value but i don't have any value. 
Currently i'm resetting my sensor to an empty value at midnight. But i can also use NaN or None or whatever. Any non integer value AFAIK.

What i would expect is to simply draw no bar.. just an "empty placeholder" till the value is available.
Maybe you make the "use_last_value" configurable? to something like "empty value" or "skip" or something else?

Do you think such a change is possible? 

I've checked quickly the utility_meter but this also doesn't fit my use-case. As the value is not an increase or decrease value . 

More or less i receive a kind of random value for each day. And i don't want to display any other value till the value is available.

Thanks

**Comment by auveele** [comment] 2021-01-15 14:01
> Hi,
> 
> ah okay.. i see the problem.
> The problem here is that if i set it to 0 its not correct.. because 0 would be a valid value but i don't have any value.
> Currently i'm resetting my sensor to an empty value at midnight. But i can also use NaN or None or whatever. Any non integer value AFAIK.
> 
> What i would expect is to simply draw no bar.. just an "empty placeholder" till the value is available.
> Maybe you make the "use_last_value" configurable? to something like "empty value" or "skip" or something else?
> 
> Do you think such a change is possible?
> 
> I've checked quickly the utility_meter but this also doesn't fit my use-case. As the value is not an increase or decrease value .
> 
> More or less i receive a kind of random value for each day. And i don't want to display any other value till the value is available.
> 
> Thanks

Did you find a solution for your issue?
I have the same problem with some sensors.

Thanks in advance!

**Comment by eloo** [comment] 2021-01-15 17:44
sadly no.. 
IMHO this can only be fixed properly in the card itself

**Comment by RomRider** [comment] 2021-01-20 01:49
In influxdb, there's the `fill` option. https://docs.influxdata.com/influxdb/v2.0/query-data/flux/fill/

We could see if the same approach wouldn't be too complex to implement.

**Comment by RomRider** [comment] 2021-02-14 18:16
Thanks for this feature request.

This feature is already available in [apexcharts-card](https://RomRider/apexcharts-card).
This card is probably going to stay in maintenance mode, so no new features will be added in the future.

**Comment by jlsjonas** [comment] 2022-01-23 18:21
Duplicate of #366

**Closed by jlsjonas** 2022-01-23 18:21 UTC
Labels: question, feature request, apexcharts-card
