### ISSUE TITLE
Time/hours on X axis?

### ISSUE THREAD

**Issue by clandestine-avocado** [kalkih/mini-graph-card#508] opened 2020-12-05 01:51 UTC
I don't see this as an option. Realize the goal was to keep the card relatively clutter free - but I would find it useful in a few of the cases I'm using the chart for.

**Comment by kalkih** [comment] 2020-12-26 13:04
Yes, you're correct, this is not possible right now, closing this as duplicate of #21

**Closed by kalkih** 2020-12-26 13:04 UTC
Labels: duplicate
