### ISSUE TITLE
Problems with "hours_to_show" = float value (particularly < 1.0)

### ISSUE THREAD

**Issue by QkulleQ** [kalkih/mini-graph-card#181] opened 2019-10-22 13:13 UTC
I would like to be able to show 5 min cpu load graphs.
But this means the hours_to_show option should be of type real number (0.083333) instead of integer.
Could this be made possible perhaps?
Love this very nice card btw :)

**Comment by kalkih** [comment] 2019-10-22 13:29
I actually think this should already possible, If I remember correctly I removed the integer check a while back, but there were some issues with the tooltip timestamps back then when `hours_to_show` < `1`, but I think that should be fixed now as well.

A config like this should give you a data point for each minute.
```yaml
hours_to_show: 0.083333
points_per_hour: 60
```
Give it a shot and if it works we could probably update the docs.

**Comment by maxwroc** [comment] 2019-10-22 13:40
We could do something as follows:
* instead of `hours_to_show` have a setting `timeframe_to_show`
* user should be able to specify unit after the number e.g. `1h`, `5m`, `7d`
* the default option would stay as hours (when there is no unit)
* we could make this setting backward compatible - so take hours_to_show if it is present (but remove it from documentation)

The above should be fairly simple, right? I'd like to have such option for "point_per_hour", though it can be harder to implement.

@kalkih I can work on it next weekend as long you like the idea

**Comment by kalkih** [comment] 2019-10-22 14:32
Sure, that would be great and improve usability.
As you said `points_per_hour`, is tougher, not sure how we would go about changing it, will have to think about that one. 🤔 

Something like `points_per_unit` maybe, but you would want to be able to specify a different unit than the one in `timeframe`, so maybe format like this: `6/h`, `10/m`, `1/d` etc... ?

**Comment by QkulleQ** [comment] 2019-10-22 14:38
@kalkih hours_to_show: 0.083333 is working! But the graph is plotted from left to right somehow (current time is on the left):

![1](https://user-images.githubusercontent.com/48830986/67295636-b69ee480-f4e7-11e9-9bf9-75a7592505a1.PNG)
![2](https://user-images.githubusercontent.com/48830986/67295661-c1597980-f4e7-11e9-9818-02f023e858c3.PNG)
![3](https://user-images.githubusercontent.com/48830986/67295822-f1088180-f4e7-11e9-8ce5-e02a3db794b9.PNG)

Also the time is written backwards (and without seconds):
![5](https://user-images.githubusercontent.com/48830986/67296966-835d5500-f4e9-11e9-917d-4e713bb8f685.png)

Thanks so far, I can live with the small issues!

**Comment by maxwroc** [comment] 2019-10-22 15:09
@kalkih yes I was thinking about something like this as you suggested 10/h etc

@QkulleQ I think graph is plotted correctly it is just the time which is shown not correct. Possible that I have introduced this bug recently as I remember I was adjusting this time by reducing the val by one min. Can take a look on the end of the week.

**Comment by QkulleQ** [comment] 2019-10-22 16:44
@maxwroc there's definetely something wrong with the timestamps.
For an individual point the displayed time is changing every minute, like below snapshots.
After a minute the same point is displayed with a different timestamp:

![6](https://user-images.githubusercontent.com/48830986/67304574-5498ac00-f4f4-11e9-87ee-aed3f916eaf5.png)
![7](https://user-images.githubusercontent.com/48830986/67304590-58c4c980-f4f4-11e9-8873-fb922e712e77.png)

> @QkulleQ I think graph is plotted correctly

Are you sure? The first graph of that post is the oldest snapshot. Snapshots 2 and 3 were taken after the first one. The newer points on those snapshots are added on the left side. Shouldn't that be on the right side?

I think this behavior is only happening with values below 1 for the hours_to_show option.
For example the Gas Consumption graph has a 24 hour value.
Here is the same graph somewhat later, new points are added to the right:

![8](https://user-images.githubusercontent.com/48830986/67307090-3b91fa00-f4f8-11e9-978d-d11464e05be6.png)

(BTW. notice the timestamp of the point has changed again)

**Comment by kalkih** [comment] 2019-10-24 01:03
Yeah, there's definitely something funky going on when going below `1` `hours_to_show`.
The timestamps and the graph is calculated separately and both seem wrong so probably more than one bug.

Another issue is that the graph only update/re-render when the entity state change, and in smaller timeframes like this it's def an issue, unless the sensor entity updates very frequently.
We have the update_interval option that could solve it, but that requires the user to actually set it.

The timestamps does however update on every card re-render.

**Comment by ildar170975** [comment] 2022-02-10 22:08
The issue is stalled.
There is no any reaction from the topic starter.
I cannot confirm the issue:
![image](https://user-images.githubusercontent.com/71872483/153504891-68ce1eac-dab0-401a-8000-8c511467ded8.png)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cleargrass_1_pm25
    color: green
    show_state: true
    show_points: true
hours_to_show: 0.25
points_per_hour: 120
aggregate_func: last
update_interval: 0
show:
  state: true
  points: true
  extrema: true
  name: false
  icon: false
line_width: 1
hour24: true
lower_bound: ~0
smoothing: false
```

**Comment by ildar170975** [comment] 2022-02-10 22:36
Reopen the issue!
Reproduced the problem:
![image](https://user-images.githubusercontent.com/71872483/153508191-79871133-760e-47fb-a6b3-cfd0cd138632.png)
The code is provided above.

**Comment by akloeckner** [comment] 2024-01-27 21:11
I think, the changing timestamp could just be because the binning is not fixed (e.g. start of minute until end of minute). This is only the case, when using `group_by`. If `group_by` is not used, the data points are calculated for bins, which constantly change, i.e. bins of equal size (`hours_to_show/n_points`) from *now*...

I suspect that the reversed order in which the times are shown is just a display/rounding issue. Maybe... But I haven't investigated.

**Comment by ildar170975** [comment] 2024-01-27 21:45
Interesting that now I managed to reproduce the glitch with `hours_to_show` > 1 and "integer":

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/4d6b79ea-eee8-4808-b1ff-1b6e763cae37)

although earlier it was reported with values < 1...

**Comment by akloeckner** [comment] 2024-01-27 23:03
You're also asking a lot: 120 points per hour is less than a minute, which seems to be the resolution of the interval display. 😆 Still... Or should just show the same time twice. 🤔

**Comment by akloeckner** [comment] 2024-01-27 23:12
Just to have the info here: this is where the magic happens:
https://github.com/kalkih/mini-graph-card/blob/af01df1e2a68cbdd367cf8e27ada26ea8f41d83b/src/main.js#L528

And there's some condition on points per hour and hours to show. So, this might have it's flaws. But I cannot look into this deeply right now...

**Comment by ildar170975** [comment] 2024-01-28 00:03
> 120 points per hour is less than a minute, which seems to be the resolution of the interval display. 

The sensor is updated every 30 sec.

**Closed** 2024-03-20 19:35 UTC
Labels: bug
