### ISSUE TITLE
Line for paticular degree (for example 0) and whole date instead just day of the week for specific point

### ISSUE THREAD

**Issue by guciopl** [kalkih/mini-graph-card#1107] opened 2024-05-29 08:35 UTC
I just created panel tab with whole screen mini-graph-card showing temperatures from last 365 days. It works nearly perfect but I miss two things. I cannot see exact date of the selected point, so as You can see marked red I am taking a look at lowest point but I can see only day of the week instead of date which is a bit annoying. Second thing is more cosmetic question than issue - is there a way to draw a line for example at 0 degree to make whole graph more readable?
![Przechwytywanie](https://github.com/kalkih/mini-graph-card/assets/61185430/587a9718-e4a0-4890-aa11-61242f0394f8)

**Comment by ildar170975** [comment] 2024-05-29 10:37
1. Please do not put several unrelated tasks into one issue.
2. "Line for paticular degree" - duplicate of https://github.com/kalkih/mini-graph-card/issues/570
3. "whole date instead just day of the week for specific point"- duplicate of https://github.com/kalkih/mini-graph-card/issues/1066

**Closed by ildar170975** 2024-05-29 10:37 UTC
Labels: duplicate
