### ISSUE TITLE
timeframes lacking sensor data show olderst history value

### ISSUE THREAD

**Issue by M5M400** [kalkih/mini-graph-card#540] opened 2021-01-19 09:34 UTC
Might be intended that way, but it's highly irritating for my usecase.

I created a bar graph that shows past weeks daily power consumption of a smart plug. Since I just set it up, my sensor history only covers the past two days. However, the earlier days bars just show data from yesterday instead of 0 or no bar at all.

![image](https://user-images.githubusercontent.com/22886679/105014065-3fd0fe00-5a40-11eb-8de9-5a7cb138ca56.png)

![image](https://user-images.githubusercontent.com/22886679/105014169-61ca8080-5a40-11eb-8b5e-5e0a6040cf7d.png)

![image](https://user-images.githubusercontent.com/22886679/105014225-7575e700-5a40-11eb-9c16-856841327c5d.png)

If this is intended behavior, maybe a graph config item can be added to hide bars that lack history data or show 0 values for missing plot points?

Thanks for your consideration

**Comment by RomRider** [comment] 2021-01-20 01:53
Duplicate of #414

**Closed** 2021-01-20 01:53 UTC
Labels: duplicate, enhancement
