### ISSUE TITLE
Container size changes when hovering label

### ISSUE THREAD

**Issue by maxwroc** [kalkih/mini-graph-card#189] opened 2019-10-25 16:36 UTC
Hey @kalkih, just noticed that when I hover the label, container size changes and entire UI is flickering. I'm on recent dev branch. Let me know if you are not able to repro. Hold on with releasing new ver.

**Comment by kalkih** [comment] 2019-10-25 17:29
Alright, I'm not able to reproduce, any specific browser?

**Comment by maxwroc** [comment] 2019-10-25 20:27
Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by kalkih** [comment] 2019-10-25 21:43
Can't reproduce, I got the same browser version as you on both windows and mac.

Not sure what it could be, this is really the only hover related style affecting labels I think
https://github.com/kalkih/mini-graph-card/blob/92eaa5f820e319aea202294bee841ccc8276f438/src/style.sj#L33-L36

**Comment by maxwroc** [comment] 2019-10-27 21:36
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8268674/67642050-cc554500-f8ff-11e9-81b0-4210c91b94ca.gif)

It looks like a corner case scenario as I'm only able to repro it on one graph and in some specific window size (1630px width). Graph is in 3 column view and it is located in middle bottom part. 
The reason why entire layout is jarring is because scrollbar appears and disappears when hovering.

I have tried to check what might be causing it but I cannot find anything (though I didn't spend much time).

I cannot repro it on prev version of plugin but maybe it is just a coincidence.  Anyway, as I said - it looks like a corner case scenario (exact window width, graph rendered on the bottom and it's bottom part exactly ends where page ends too), so I wouldn't spend too much time on it.

**Comment by kalkih** [comment] 2019-10-27 21:58
Alright, so something is resizing on hover...
Can you see the computed card height increase in dev tools when you hover and it glitches?

**Comment by maxwroc** [comment] 2019-10-27 22:27
Yes the card size changes but as well the other cards too - as the entire page container is smaller when scrollbar appears. That is why it is hard to tell what exactly is causing the problem.

BTW this scrollbar is a bit weird - it is inactive and it is not possible to scroll actually anything. Maybe it is a Chrome bug...

Card size:
447/230px (without scrollbar) -> 441/229px (with scrollbar)

**Comment by kalkih** [comment] 2019-10-28 13:16
I understand the card width changes when the scrollbar is added, the issue is the height, the height shouldn't change.

**Comment by maxwroc** [comment] 2019-10-28 15:43
It is just 1px diff but I will try to track it down

**Comment by kalkih** [comment] 2020-01-29 15:27
I'm closing this for now, haven't been able to reproduce it.

**Closed by kalkih** 2020-01-29 15:27 UTC
Labels: bug
