### ISSUE TITLE
color thresholds: wrong line color

### ISSUE THREAD

**Issue by nschloe** [kalkih/mini-graph-card#893] opened 2022-12-22 10:28 UTC
I have a mini-graph-card with some color thresholds:

```yaml
type: custom:mini-graph-card
entities:
  - sensor.bogenhanf_conductivity
align_icon: left
align_state: left
show:
  fill: true
hours_to_show: 336
lower_bound: 0
upper_bound: 2500
color_thresholds:
  - value: 300
    color: '#D0342C'
  - value: 301
    color: '#008000'
  - value: 1000
    color: '#D0342C'
color_thresholds_transition: hard
```

The dots (shown when hovering over the graph) have the correct color, but the line doesnt:

![s2](https://user-images.githubusercontent.com/181628/209114189-9f39d494-58d5-48c4-a931-6f5b602ab46a.png)

![s1](https://user-images.githubusercontent.com/181628/209114207-b4bcd8b8-ef26-4d10-b730-680c47e1fc2d.png)

It doesn't matter if the transition is hard or smooth

**Comment by jlsjonas** [comment] 2022-12-24 01:00
Hi,

There seems to be a drift on the linear gradient when setting a higher `upper_bound`.

If you need the color at a glance I'd recommend to either remove the `upper_bound` or set show option's `points: true`

**Comment by nschloe** [comment] 2022-12-24 09:41
Observe the red and green area below the graph: They're also incorrectly computed. Perhaps the bug has something to do with that.

**Comment by ildar170975** [comment] 2024-01-20 05:28
@nschloe 
1. Cannot reproduce your issue.

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/7c912329-a1f8-4957-a49a-bb43fe451ab0)
Code for the 1st card:
```
type: custom:mini-graph-card
name: 'lower_bound: ~400'
entities:
  - sensor.xiaomi_cg_1_co2
show:
  fill: true
  labels: true
hours_to_show: 48
height: 500
line_width: 2
lower_bound: ~400
upper_bound: 1000
color_thresholds:
  - value: 400
    color: green
  - value: 500
    color: red
  - value: 600
    color: blue
color_thresholds_transition: hard
```

2. Please post screenshots in a way to make them more visible.
> red and green area below the graph

On your screenshots this is rather subtle. Use a default light theme next time.

**Comment by nschloe** [comment] 2024-01-21 13:46
All your transitions are quite sharp. Try it with flatter data near a color threshold.

**Comment by ildar170975** [comment] 2024-01-21 21:31
> All your transitions are quite sharp.

This is good.

> Try it with flatter data near a color threshold.

What can it change?

![image](https://github.com/kalkih/mini-graph-card/assets/71872483/358e7c57-ed1b-4dee-95e0-25486ec71760)
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_number.number
  - type: custom:mini-graph-card
    entities:
      - input_number.number
    show:
      fill: true
      labels: true
    hours_to_show: 0.083333
    height: 500
    cache: false
    line_width: 2
    lower_bound: 0
    points_per_hour: 600
    smoothing: false
    color_thresholds:
      - value: 0
        color: green
      - value: 10
        color: red
      - value: 20
        color: blue
    color_thresholds_transition: hard
```

**Comment by nschloe** [comment] 2024-01-22 15:15
> This is good.

Well, mine aren't and that cause the problem. If the transition is shallow, colors aren't correctly assigned.

**Comment by ildar170975** [comment] 2024-01-22 19:47
What is a “shallow” transition?
There are 2 types of transition. 
If you mean “smooth” - then take MY example, change to “smooth” and please show what is wrong there.

**Comment by nschloe** [comment] 2024-01-23 07:19
Sorry, my wording was unclear. In your examples, the graphs "dive" sharply from one area to the next. In my example, the y-value hardly changes. Over the whole x-length of the graph, it creeps down:

![i1](https://github.com/kalkih/mini-graph-card/assets/181628/58ffc8d7-a95a-4542-b38f-5d0a2ba27599)

From looking at it, it seems that everything is still in the green. That's wrong though! The transition into the "red" color area has already happened, and is revealed when hovering with the mouse pointer over the image to such that the points are highlighted:

![f](https://github.com/kalkih/mini-graph-card/assets/181628/75a46e57-3755-4fb7-b9bf-99fce198436d)

I hope this makes things clearer.

**Comment by ildar170975** [comment] 2024-01-23 07:43
Already suggested you to make graphs more clear - height, theme. 
Sorry, can barely see.

**Comment by nschloe** [comment] 2024-01-23 07:46
> Sorry, can barely see.

Can you see that the graph is completely green in the above chart, and red on the right-hand side in the below graph?

**Comment by ildar170975** [comment] 2024-01-23 07:48
Perhaps someone may use a loupe and help you.

**Comment by nschloe** [comment] 2024-01-23 08:49
I'm really at a loss tring to explain the issue. Last attempt:

![rnr](https://github.com/kalkih/mini-graph-card/assets/181628/8a2c26c2-eb5e-4b87-8668-cb038cf96527)

Two pictures of the same data, going from green to red. Top is with mouse hover, so the little data points are visible. They are red; good. Bottom: Just the graph lines. All green; not good.

**Comment by ildar170975** [comment] 2024-01-23 11:30
You got an issue which you want to sort out. 
For this you need to simplify the case - to make it clear. 
Twice I suggested you how we can simplify it - increase height and make colors clearly visible by using a light default theme. 
Let’s not spent a lot of time and posts for discussing a necessity of these suggestions; and in the end we might still not be able to solve the issue. But it may help.

**Comment by ildar170975** [comment] 2024-01-27 19:16
Also, thresholds were set in a wrong way:
```
  - value: 300
    color: '#D0342C'
```
i.e. starting from "300", but actual data may be below 300 which causes inconsistency.

**Comment by ildar170975** [comment] 2024-05-01 12:54
No feedback within 3 months, closing

**Closed by ildar170975** 2024-05-01 12:54 UTC
Labels: question
