### ISSUE TITLE
[Feature Request] - color_thresholds_secondary

### ISSUE THREAD

**Issue by rechichidaniel** [kalkih/mini-graph-card#907] opened 2023-01-15 14:52 UTC
Can you please add a way to set different colour thresholds for the secondary axis? This would be useful when graphing both temperature and humidity in the same space.

**Comment by ildar170975** [comment] 2023-01-21 23:51
duplicate of https://github.com/kalkih/mini-graph-card/issues/153

**Closed by ildar170975** 2023-01-21 23:51 UTC
Labels: duplicate
