### ISSUE TITLE
Cannot assign to read only property '0' of object '[object Array]' / 0 is read-only

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [kalkih/mini-graph-card#338] opened 2020-04-22 12:24 UTC
I don't know why, but I get following error on a normal sensor, which works fine with a normal history graph:

```
Cannot assign to read only property '0' of object '[object Array]'
```

Any ideas?

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-04-22 12:26
Ops, had an old version... Updating to the latest one fixed the problem 👍

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-04-22 12:40
Ok, it worked for some minutes.. And now I get this error again :(

I didn't change anything to my sensors?

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-04-22 12:43
And to make it even more strange, the error above is happening in Chrome.
Using Firefox I get another error, for the same configuration:

```
0 is read-only
```

**Comment by kalkih** [comment] 2020-04-22 14:53
Hello yes, duplicate of #274, #275, #284, #285, #286, #287, #290

> This has been fixed in the latest version of the card released a few days back.
>
> If you still have the issue after updating the card that means your browser isn't loading the updated version of the card. Try the following:
> 
> Reinstall the card in HACS (if installed though HACS)
> Double check the resource reference (if installed though HACS), make sure it match the one in HACS #169
> Clear browser cache
> If you still have issues after this, open the browser developer console (google how to do this) and look for a line which says "MINI-GRAPH-CARD" followed by the version number and let me know what version it says.

**Closed by kalkih** 2020-04-22 14:53 UTC
Labels: duplicate

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-04-22 15:02
Thanks!

I had 2 resources included as it seems, removing the old one fixed this problem!
Thank you very much!
