### ISSUE TITLE
From comma to dot thousands separator

### ISSUE THREAD

**Issue by Disincentivato** [kalkih/mini-graph-card#1125] opened 2024-08-15 17:20 UTC
I read in a 2021 post that the thousands separator with the new versions will adapts to the language set in HA.
In my case it remains wrong, I have a comma instead of a dot.
Do I mess something?

Thanks a lot!
Fabrizio 

![image](https://github.com/user-attachments/assets/8314afe8-fbec-46d5-95ec-240c8132888f)

**Comment by ildar170975** [comment] 2024-08-21 22:05
Duplicate of https://github.com/kalkih/mini-graph-card/issues/1010

**Closed by ildar170975** 2024-08-21 22:05 UTC
