### ISSUE TITLE
Feature request: reference lines

### ISSUE THREAD

**Issue by snis** [kalkih/mini-graph-card#80] opened 2019-04-03 10:27 UTC
I would like to be able to add reference lines (Y axle) with possibility to change color and width. The line should not fill the area below and should be rendered behind the entity sensors if possible.

In a temperature graph a line for 0C/32F would make sense. Or a threshold line (calculated from a template) showing average server loads or temperature.

![graph2](https://user-images.githubusercontent.com/205149/55472213-d209d700-560b-11e9-8a82-8b235bed4318.png)

**Comment by noisemaker00** [comment] 2019-12-20 10:45
I would like this too, in particular for temperature chart (eg. 0°C reference).
How can I achieve that? Has the feature already been released?

**Comment by kalkih** [comment] 2019-12-20 22:42
No this hasn't been implemented yet.

You could technically set up a template sensor and assign it a constant value of which you want the reference line to display (`0` in your case I guess), then use that entity in the card and utilize the various show options to adjust the visuals of it, I would recommend hiding points for example.

**Comment by mmiller7** [comment] 2020-02-23 20:36
I'd also very much like this feature - I thought this would be a good fix for having a graph with fixed scale max/min (hassio's graph apparently can't) but the lack of grid-lines to glance and see what the intermediate values are without having to trace every point with the mouse is a deal-breaker.

**Comment by StefanoGiu** [comment] 2020-04-23 09:50
Interested in this... following

**Comment by JJFourie** [comment] 2021-01-10 17:17
This would indeed be very useful and appreciated.

As the graph currently does not have any grid lines (pending a submitted feature request), it is not all that easy to orient the line with respect to reference values.
In addition, it would be nice to (optionally) also make it possible to set a "legend" for the line.

So to summarize, make it possible to configure:

1)    Reference line for each value provided.
2)    Display the line description if configured (optional).
3)    Nice to have: make it possible to configure the line appearance
       -    line color
       -    thickness
       -    dashed/solid

Below: example of a graph with three reference lines, each with a description.

![RainCard-Light](https://user-images.githubusercontent.com/49686555/104130119-4fc94d80-536f-11eb-8ff1-a85fad71dd67.jpg)

**Comment by RomRider** [comment] 2021-01-17 19:38
Duplicate of #21

(let's discuss it there while I'm trying to wrap my head around the codebase :))

**Closed by RomRider** 2021-01-17 19:38 UTC
Labels: feature request
