### ISSUE TITLE
FR: Allow templates and/or input_numbers in color_threshold values

### ISSUE THREAD

**Issue by sciurius** [kalkih/mini-graph-card#852] opened 2022-10-19 14:52 UTC
I would like to be able to write
````
color_thresholds:
  - value: 0
    color: "#00ff00"
  - value: input_number.some_threshold
    color: "#ff0000"
````
Alternatively, support for templates would be nice, e.g.
````
  - value: "{{ states('input_number.ithocve_humidity_threshold') }}"
````

Thanks,

**Comment by jlsjonas** [comment] 2022-10-19 18:39
Duplicate of #697

**Closed by jlsjonas** 2022-10-19 18:39 UTC

**Comment by sciurius** [comment] 2022-10-20 06:07
Okay, but shall we keep the input_numbers part?

**Comment by ildar170975** [comment] 2022-10-20 22:29
> shall we keep the input_numbers part?

Better to be implemented as a template.
